### ISSUE TITLE
resolver = 2 breaks downstream crates with msrv lower than 1.51.0

### ISSUE THREAD

**Issue by robjtede** [rustls/rustls#1003]
Unless there's a reason you _need_ resolver 2, it might be good to wait until edition 2021 (which defaults to resolver 2) is more commonly used among library authors.

For example, we (actix-net repo) are getting [CI failures](https://github.com/actix/actix-net/runs/5193449628?check_suite_focus=true) now with a (partial) [MSRV of 1.46](https://github.com/actix/actix-net/blob/master/.github/workflows/ci.yml#L121).

And I'm guessing next time `hyper-rustls` has a CI run it will happen too with its [MSRV 1.50.0](https://github.com/rustls/hyper-rustls/blob/main/.github/workflows/build.yml#L20).

**Comment by djc** [comment]
rustls CI has already been testing for 1.52.1 since before the 0.20 release. 0.20.0-0.20.2 did actually support 1.50, but we never supported anything older for 0.20. I believe this is pretty reasonable -- many crates use an MSRV policy of around 6 months old language/compiler releases.

**Comment by robjtede** [comment]
> I believe this is pretty reasonable -- many crates use an MSRV policy of around 6 months

Totally agree it's reasonable even though my personal preference veers towards MSRV bumps being always breaking changes. The particular issue with resolver 2, more than other MSRV problems is that pre-1.51 cargo cannot even parse the manifest, let alone compile the code. It's a form of breakage that is insidious and very annoying to deal with in mixed MSRV repos like actix-net.

That's my piece, happy to work around whatever the maintainers here decide.

**Comment by djc** [comment]
I think the ship has sailed in terms of MSRV bumps being breaking changes -- most crates don't do that.

What kind of MSRV policy are you striving for with actix-net? If we were to revert the `resolver = "2"` changes, how long before we can reintroduce that? (TBH, I have a hard time seeing any answer to this question that'll make us actually revert -- I think my 6 months stance is actually the most conservative within the rustls team.)

**Comment by robjtede** [comment]
> how long before we can reintroduce that

imho, when you bump to using edition = 2021

**Comment by ctz** [comment]
I would be happy to back out the resolver=2 change and push a 0.20.4, but -- unless we also reduce our tested MSRV there will be a good chance that something else will break in the future. It is somewhat accidental that we aren't currently relying on any changes between 1.46 and 1.52.

**Comment by robjtede** [comment]
When using resolver 2 it's more like an MSCR (minimum supported _Cargo_ version) since the code itself if never gets compile on the CI job I linked to, I only need it to **parse the manifest** on pre-1.51. So this is different in nature to hyper-rustls which will need to match your MSRV really.

That said, I've found a workaround for my specific use case by [pinning to 0.20.2 in the before anything](https://github.com/actix/actix-net/blob/master/.github/workflows/ci.yml#L147) reads manifests.

**Comment by briansmith** [comment]
@robjtede First of all, I think the workaround you implemented is a good one. Thanks for sharing it.

I am the one that made the changes to set the MSRV to 1.52.1 and to add resolver=2, even though Rustls currently doesn't use 1.52.1 features and technically works with resolver=2.

I did the MSRV change because I want to avoid "forcing" Rustls to suddenly bump its MSRV when I make updates to *ring* and/or webpki. I don't feel like Rustls should dictate the *ring*/webpki MSRV policy but at the same time, I want to be cooperative and friendly about it. The PR I submitted and the related discussions are how we come about a friendly agreement on the matter.

Regarding resolver=2, I think it matters less now, but it will matter more soon. I am hoping we can make Rustls support no_std environments that have `alloc` soon. resolver=2 will become important for enabling that. Again, I decided to submit the change for resolver=2 earlier than strictly necessary so that when we really *need* resolver=2, it doesn't cause an emergency.

Now, being a little more opinionated: Rust 1.51 with the minimal const generics is a major improvement in the language. I don't think anybody should bother trying to support earlier versions of Rust any longer. Similarly, resolver=2 is technically an "enhancement" but resolver=1 behavior is so problematic that I consider it a critical bugfix.

Being even more opinionated: This project, my projects, and almost every open source project is severely resource constrained. We have to optimize for forward progress, and doing that means limiting how much inertia we allow to apply to our projects. MSRV policies are one of the things that create inertia that prevent forward progress.

Concretely, it looks like Rust 1.59 will be a very important release for *ring* as it will enable much more stuff to be moved from C to Rust, because it will add inline assembly support. So I am hoping we can agree that 1.59 will become the MSRV of Rustls very soon. For that reason, I'm particularly uneager to move backward.

**Comment by robjtede** [comment]
Thanks for leaving your thoughts here @briansmith. I think I need to leave my extremist MSRV-breaking-change policy behind. It's clear from the Rust community as a whole that it is an acceptable form of breakage. Particularly in this case, as you mentioned `no_std` support, I understand the desire to start using resolver 2 separately from edition 2021.

My workaround is more than satifsactory until I bump MSRV on our CI.

**Comment by djc** [comment]
@briansmith thanks for the explanation! I was searching for the motivation for your resolver = 2 change in the issue tracker and the PR and couldn't find anything, so it's good to have it here at least.

**Comment by briansmith** [comment]
> @briansmith thanks for the explanation! I was searching for the motivation for your resolver = 2 change in the issue tracker and the PR and couldn't find anything, so it's good to have it here at least.

Sorry. Definitely I should have left a better commit message. I am refactoring parts of *ring* and webpki w.r.t. how features are used, and I wanted to check to see if anybody objected to using the new feature resolver. It's important for *ring* to use the new resolver because it has some heavy dev-dependencies.
