### ISSUE TITLE
rustls_pemfile fails to load openssl-generated private key

### ISSUE THREAD

**Issue by jgarzik** [rustls/rustls#1079]
Summary:  A private key generated by openssl(1) is not properly parsed by `rustls_pemfile`.

A full repository with scripts and source code to reproduce the issue was created at: https://github.com/jgarzik/rustls-pemfile-issue

Found this showstopper issue while attempting to convert my actix+openssl HTTPS server to rustls: https://github.com/jgarzik/kvdbd/tree/rustls

The demonstration code that fails is straight out of rustls examples: https://github.com/rustls/rustls/blob/main/rustls/examples/internal/bogo_shim.rs#L168

**Comment by thalesfragoso** [comment]
The default format for openssl generated private keys is not standard. You can use the pkcs8 openssl command to convert it to a standard one.

**Comment by jgarzik** [comment]
Is this project willing to consider a strong rationale for supporting it anyway?

* It is incredibly commonly found in the field
* possibly _the_ most common openssl(1)-generated format historically?
* it is what is generated by default by most online "create a self-signed cert" instructions.
* Some folks cannot regenerate their private key

What is needed to support this old-but-highly-common standard?

The alternative will require each individual server developer to add this support code anyway, implying that rustls inclusion is a more efficient way to accomplish what will be the inevitable outcome anyway (developers having to code some autodetect-and-convert into every HTTPS server init).

**Comment by ctz** [comment]
bogo_shim.rs is not really intended as example code which is why it's in an internal directory. Please instead use https://github.com/rustls/rustls/blob/0053c4d59be76b5d424582ca576d1b98942fdd60/rustls-mio/examples/tlsserver.rs#L521 which will load these keys.

The underlying issue is that code uses `rustls_pemfile::pkcs8_private_keys` and these keys are not PKCS#8 format. As you can see the recommended code loads multiple kinds of key formats.

**Comment by jgarzik** [comment]
That makes sense, thanks.  I'll delete my incorrect demo repo.

Appreciate the correction.
