### ISSUE TITLE
Add support for latest BoGo updates

### ISSUE THREAD

**Issue by jbr** [rustls/rustls#1158]
current output, running against unpatched google master (396625d50212143bc03517c9fdd21b1c965b3f45): https://gist.github.com/jbr/8d2a0d96719132f06666ff47544d8c89

it looks like there are unsupported flags on the shim as well as reported failures

**Comment by djc** [comment]
So far I see two major categories:

* Unexpected error outputs, like `EmptyCertificateList` seems to expect `:DECODE_ERROR:` now instead of `:NO_CERTS:`. Usually we don't care that much exactly how we error out. The `bogo_shim` maps errors in `handle_err()` and there are `ErrorMap` and `TestErrorMap` keys in `bogo/config.json` that you can use here.
* `unhandled option`, I think we can print `NYI` to signal that a feature is Not Yet Implemented. Would probably be a good start to do that for everything that's unhandled now, but it would be useful if you can make a list of the features it's asking about. We should probably support `-reject-alpn`, but we don't yet support ECH (https://github.com/rustls/rustls/issues/199).

(Probably good if you can add all this stuff to the `bogo/README.md`!)

**Comment by djc** [comment]
@ctz do you want to keep some open issue for documenting a few of the things I mentioned in my previous comment?
