### ISSUE TITLE
Conversion from webpki::Error to Rustls::Error is private

### ISSUE THREAD

**Issue by jadamcrain** [rustls/rustls#1276]
https://github.com/rustls/rustls/blob/5c81497d79d21c27983f46c9104407266ab4b511/rustls/src/verify.rs#L654

It would be helpful to users who have custom verifiers if this was the trait impl `From<webpki::Error> for rustls::Error` and available outside the crate.

In our projects, we have to set custom client/server verifiers. Most of it is just like the default webpki verifier, except that we also allow the subject name to match against the common name. The  certs in some machine-2-machine PKIs we support don't used the SAN extension, so we have to by-pass this limitation in webpki.

If I submit a PR to change this to a `From` would you consider it?

**Comment by djc** [comment]
This is intentional, we want to keep webpki as a private dependency so we can accomodate updates to webpki versions with API-incompatible changes without affecting the public rustls API. If you maintain your own verifier, it doesn't seem like a significant chore to also maintain a copy of the error mapping (although I understand that it's suboptimal).

**Comment by jsha** [comment]
Some additional information that might be useful:

 1. Rustls now depends on a fork of the original webpki crate, rustls-webpki: [repository](https://github.com/rustls/webpki), [crate](https://crates.io/crates/rustls-webpki), [docs](https://docs.rs/rustls-webpki/0.100.1/webpki/).
 2. It's unlikely that we would accept a patch that validates a hostname in the Subject Common Name field when that hostname is not present in the Subject Alternative Names field. That's been a longstanding misfeature of server certificate verification that is now (mostly) fixed in the wild.
 3. If this is for client certificate validation, it would be useful to post details about your use case here: https://github.com/rustls/rustls/issues/1164

**Comment by jadamcrain** [comment]
`That's been a longstanding misfeature of server certificate verification that is now (mostly) fixed in the wild.`

@jsha You're right of course for the **Web PKI**. Industrial controls systems using TLS for mutually authenticated security are another story altogether. Flexible name validation is still required for these systems both for server and client cert validation unfortunately.
