### ISSUE TITLE
Disabling hostname checking?

### ISSUE THREAD

**Issue by naturecodevoid** [rustls/rustls#1291]
Hi, sorry if this is not the right place to ask. Is it possible to disable hostname checking? I'm planning to use rustls with a unix socket, which can't really be represented as an IP (unless it accepts 127.0.0.1). A Python implementation of communicating with the same unix socket just disables hostname checking, so I think I'll need to do the same.

**Comment by cpu** [comment]
Hi @naturecodevoid,

> sorry if this is not the right place to ask

No worries, you're in the right place :-)

>  Is it possible to disable hostname checking?

Yes, but I believe it will require you to do a little bit of plumbing and use the `dangerous_configuration` feature. This isn't something offered out-of-box due to safety concerns.

You can control the verification process for a client by implementing the [`ServerCertVerifier` trait](https://docs.rs/rustls/latest/rustls/client/trait.ServerCertVerifier.html#) and modifying your client config to use your verifier.  Take a look at the default [`WebPkiVerifier`](https://docs.rs/rustls/latest/rustls/client/struct.WebPkiVerifier.html#) for somewhere to start. In essence you'll want to implement the [`verify_server_cert`](https://docs.rs/rustls/latest/rustls/client/trait.ServerCertVerifier.html#tymethod.verify_server_cert) logic there minus the check that the end-entity certificate `end_entity` is valid for the hostname `dns_name`.

The above is assuming you still want to require the end entity certificate chains to a trusted root and isn't expired. If you want to disable certificate validation entirely you take the simpler approach the [`tlsclient-mio` example uses](https://github.com/rustls/rustls/blob/5384985c65836fe85f47116400228bf231420fd2/examples/src/bin/tlsclient-mio.rs#L337C18-L354) (_just make sure you understand the danger and that it fits your threat model!!_).

Hope that helps,

**Comment by naturecodevoid** [comment]
Thank you so much, that helps a ton! I'll try implementing ServerCertVerifier first, but I have a feeling I'll have to disable certificate verification entirely. I'll close this issue for now, if I have any questions in the future I'll reopen this.

**Comment by naturecodevoid** [comment]
I was able to get it to work with no certificate verification first try. Thank you so much for the help!
