### ISSUE TITLE
Connection from TLS 1.2 client without Signature Algorithms Extension fails

### ISSUE THREAD

**Issue by sludin** [rustls/rustls#1364]
TLS 1.3 clients are not required to send the Signature Algorithms Extension ( from [RFC 5246](https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.4.1) ):

"If the client supports only the default hash and signature algorithms (listed in this section), it MAY omit the signature_algorithms extension."

It seems that rustls insists on the extension being present (from server/hs.rs, process_client_hello):

```
     let sig_schemes = client_hello
        .get_sigalgs_extension()
        .ok_or_else(|| {
            cx.common.send_fatal_alert(
                AlertDescription::HandshakeFailure,
                PeerIncompatible::SignatureAlgorithmsExtensionRequired,
            )
        })?;
```

This looks like a hard error with no way to get around it.  A CDN is sending TLS 1.2 requests without this extension to my 'server in development' and the rustls layer is rejecting them.

**Comment by ctz** [comment]
Hi, thanks for the report.

We do require this extension, because the "default hash and signature algorithms" mentioned in that bit of the RFC aren't supported, because they all rely on (the very-much-broken) SHA1.

Those CDN requests are saying "please only use RSA/DSA/ECDSA SHA1 signatures." It might be worth asking the CDN in question if they meant to do that. Maybe point them towards NIST SP800-131A: "SHA-1 shall not be used for digital signature generation after December 31, 2013."

**Comment by sludin** [comment]
Yes, I see (Again, RFC 5246): 

"If the negotiated key exchange algorithm is one of (RSA, DHE_RSA, DH_RSA, RSA_PSK, ECDH_RSA, ECDHE_RSA), behave as if client had sent the value {**sha1,rsa**}"

I'll kick this around a bit. Unfortunately in the world of bad choices, between rustls changing, the CDN changing, and me using something besides rustls, there is only one thing I have direct control over!

Thanks for your response.

**Comment by djc** [comment]
Which CDN is this? Would be helpful for us to correlate issue reports?
