### ISSUE TITLE
`DecryptError` in case of unknown certificate

### ISSUE THREAD

**Issue by thegreathir** [rustls/rustls#1369]
The `OpenSSL` is sending unknown CA alert without encryption. It's different from browsers that are sending every alert after handshake encrypted. When you are trying to connect to a `rustls`  server with a `OpenSSL` client without knowing the server's CA, `rustls` will produce `DecryptError` instead of `AlertReceived`.

To reproduce run a `rustls` server:
```bash
cargo run --bin tlsserver-mio -- --certs ~/tmp/cert/server.crt --key ~/tmp/cert/server.key -p 8000 http
```
And an `OpenSSL` client (`pip` is used here):
```bash
pip3 install -i https://127.0.0.1:8000 --trusted-host sample.host.com package_name
```

**Comment by djc** [comment]
I can test this later, but I think this might be due to refactoring I worked on in the MessageDeframer. It seems likely we need a similar path for Alert as we have for ChangeCipherSpec.

If you want to try your hand at a PR and/or turn this failure scenario into an integration test, that would be great!

**Comment by djc** [comment]
What version are you using? I tried this:

```
cargo run --bin tlsserver-mio -- --certs test-ca/ecdsa/end.cert --key test-ca/ecdsa/end.key -p 8000 http
```

And got this:

```
djc-2021 ~ $ pip3 install -i https://127.0.0.1:8000 --trusted-host sample.host.com package_name
Looking in indexes: https://127.0.0.1:8000
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /package-name/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /package-name/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /package-name/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))': /package-name/
```

**Comment by thegreathir** [comment]
Last version. You should add a `--version` option to `tlsserver-mio` then you would see the following line in the output:
```
[2023-07-24T16:37:33Z ERROR tlsserver_mio] cannot process packet: DecryptError
```

But if you try to open the link in Firefox (A browser that sends certificate alert encrypted) following line will appear instead:
```
[2023-07-24T16:39:46Z ERROR tlsserver_mio] cannot process packet: AlertReceived(BadCertificate)

```

**Comment by djc** [comment]
Thanks for digging in! If nothing else, we have a good reason not to make changes on our side. I suppose there are two questions here: (1) should we, as a sender, send our alerts encrypted where possible, and (2) should we support reading unencrypted alerts from the peer? I think the answer to (1) is a clear yes, but for (2) it doesn't seem crazy to suggest that our users would get a better experience if we supported both? Then, if it's not too hard, maybe the answer to (2) is also yes.

> I think this proposed fix needs to be a little bit more nuanced. If we update the condition in the deframer that returns early for CCS messages to do the same for `m.typ == ContentType::Alert` we will break handling encrypted alerts - they'll also be returned early before decrypting the content and `m.into_plain_message()` will error after finding unexpected trailing (ciphertext) data.

That's fair. I guess my question is if the deframer can reliably detect unencrypted payload for messages with `ContentType::Alert`. Given that an `AlertMessagePayload` is pretty short (substantially shorter than the MAC), that seems pretty easy?

**Comment by ctz** [comment]
It's a bit tricky, because if we allow unencrypted/unauthenticated alerts at any point then they can be injected at any point. That would mean the protection against truncation that `close_notify` provides would no longer be effective, and probably more shenanigans on top of that.

I think we should only accept unencrypted alerts that are received before the first CCS (TLS1.2) or after the non-retry `ClientHello`/`ServerHello` (TLS1.3). As it happens, I think that is what we currently do, though I'm not sure we have explicit tests for it.

**Comment by cpu** [comment]
> (1) should we, as a sender, send our alerts encrypted where possible

Good point, I haven't looked at the Rustls client behaviour here.

> I think we should only accept unencrypted alerts that are received before the first CCS (TLS1.2) or after the non-retry ClientHello/ServerHello (TLS1.3). As it happens, I think that is what we currently do, though I'm not sure we have explicit tests for it.

In this case I think we are receiving an unencrypted alert after a non-retry ServerHello and not handling it as plaintext. It sounds like you think that should be changed or did I misunderstand?

**Comment by ctz** [comment]
Ah, this has come up in the mailing list: https://mailarchive.ietf.org/arch/msg/tls/Fksflm9IwUGnD5y9aObHjwAN9_s/

**Comment by cpu** [comment]
> (1) should we, as a sender, send our alerts encrypted where possible

I think this is already happening. Certainly for the case described in this issue we are. A rustls TLS 1.3 client that encounters an unknown CA error after the same series of server message described above responds with a CCS message and then an encrypted application layer data opaque record type with an inner alert.

> Possibly we could relax that to allow plaintext alerts prior to the first encrypted message?

@ctz I think that would be workable, what do you think of a diff like this (_needs tests_): https://github.com/cpu/rustls/tree/cpu-1369-wip

That update produces the expected behaviour with an `openssl` client (and breaks no existing tests).

Some thoughts:
* I needed to expose the `RecordLayer` read seq to be able to make a determination about whether we've received an encrypted message. Is that palatable? 
* I kept the size heuristic suggested by @djc, requiring that the payload be what we expect for a plaintext alert.
* Should we be limiting this to TLS 1.3? If so, I'm not sure the best way to pipe through an understanding of the negotiated protocol to the deframer, at the moment it seems agnostic of that (or I'm missing something obvious).

After working this branch up I was doing more Googlin' and happened to notice that the tls-fuzzer folks bumped into this same issue and fixed it **today** (coincidences abound): https://github.com/tlsfuzzer/tlslite-ng/pull/499 Their fix looks quite similar to what I'm proposing in my branch. FWIW it looks like they decided to scope this to TLS 1.3+.

**Comment by tomato42** [comment]
> FWIW it looks like they decided to scope this to TLS 1.3+.

(with the tlsfuzzer hat on) that's because in TLS 1.2 and earlier we have CCS to indicate when a peer started to use encryption, in TLS 1.3 we need to guess. And unfortunately, if the requirement is to pass in to the calling application the reason for connection abort, passing in the alert description in case we got an alert early in the handshake, means that both encrypted and unencrypted alerts need to be supported (and while it's a bit ugly, handling of early_data isn't much cleaner)

**Comment by cpu** [comment]
> (with the tlsfuzzer hat on) 

(:wave:) Thanks @tomato42 :+1: That's helpful context.

> I'm not sure the best way to pipe through an understanding of the negotiated protocol to the deframer,

Probably passing the `common_state.negotiated_version` as a parameter to the deframer `pop` would work. There's only one call-site, in `conn.rs`'s `deframe`.

I'm going to work with that + look at opening a PR with test coverage included.

**Comment by cpu** [comment]
This is now fixed in `main`. Thanks!
