### ISSUE TITLE
Catch TCP connection drop by server under io-uring

### ISSUE THREAD

**Issue by serzhiio** [rustls/rustls#1371]
Anyone knows the right way to catch a client connection drop by remote server under io-uring?
In my case i catch it only after i try send new data and try to read response which in turn give me this set to true `if io_state.peer_has_closed() {***}`.
I hope there is other way, maybe excessive zero read or smth.

**Comment by serzhiio** [comment]
The thing is i receive this only when starting to read incoming data after sending something. Id like to know is there a way to check stream without sending data in it?

**Comment by Ralith** [comment]
Configure TCP keep-alives?

**Comment by jsha** [comment]
This isn't really a rustls question so much as a TCP behavior question, but since I happen to know the answer, here's a link to how we do it in ureq: https://github.com/algesten/ureq/blob/4a2ecdf123fceb44b5e0e74c48c14930ca1c715e/src/stream.rs#L207-L238

Basically, if the server has closed a connection and the client OS knows about it, you can try to find out that fact by doing a small non-blocking read on the socket. Note that the exact technique you use will depend on how you wrap the connect using rustls; ureq uses [`StreamOwned`](https://docs.rs/rustls/latest/rustls/struct.StreamOwned.html).

Also note that this is naturally an imperfect solution. It's always possible that the server closes the connection between when you check and when you send data. But it can help significantly reduce avoidable errors when reusing connections in request-response protocols.

**Comment by serzhiio** [comment]
> This isn't really a rustls question so much as a TCP behavior question, but since I happen to know the answer, here's a link to how we do it in ureq: https://github.com/algesten/ureq/blob/4a2ecdf123fceb44b5e0e74c48c14930ca1c715e/src/stream.rs#L207-L238
> 
> Basically, if the server has closed a connection and the client OS knows about it, you can try to find out that fact by doing a small non-blocking read on the socket. Note that the exact technique you use will depend on how you wrap the connection using rustls; ureq uses [`StreamOwned`](https://docs.rs/rustls/latest/rustls/struct.StreamOwned.html).
> 
> Also note that this is naturally an imperfect solution. It's always possible that the server closes the connection between when you check and when you send data. But it can help significantly reduce avoidable errors when reusing connections in request-response protocols.

I'm trying to do this read, but with `io-uring` it is a bit tricky, and still sometimes i miss drops.

**Comment by serzhiio** [comment]
> Configure TCP keep-alives?

Already tried but can't get required result.
