### ISSUE TITLE
0.22 release planning

### ISSUE THREAD

**Issue by djc** [rustls/rustls#1435]
Let's gather some context on what we should fix before pushing out the next semver-incompatible release.

- [x] https://github.com/rustls/rustls/issues/1437
- [x] https://github.com/rustls/rustls/issues/1472
- [x] https://github.com/rustls/webpki/issues/159
- [x] #1414
- [x] #1492 
- [x] https://github.com/rustls/rustls/issues/1386
- [x] https://github.com/rustls/rustls/issues/1409
- [x] https://github.com/rustls/rustls/pull/1432
- [x] https://github.com/rustls/rustls/pull/1405
- [x] https://github.com/rustls/rustls/pull/1448
- [x] https://github.com/rustls/rustls/pull/1430 (needs a solution for verifier composability that doesn't involve webpki leaking into rustls API)

Some potential validation we could do:

- [x] Port tokio-rustls to 0.22
- [ ] Port hyper-rustls to 0.22 - https://github.com/rustls/hyper-rustls/pull/222
- [ ] Port quinn to 0.22
- [ ] Port trust-dns to 0.22

**Comment by djc** [comment]
@jsha anything else on your mind?

**Comment by jsha** [comment]
Filed #1437; that's all I can think of at the moment. Thanks for organizing this list.

**Comment by djc** [comment]
Some updates:

* Added #1437 to the list
* Replace tentative bullet for `CryptoProvider` dynamic dispatch with link to #1448 
* Added #1472 to the list

**Comment by ctz** [comment]
I think I'd like to get #1414 in too.

**Comment by ctz** [comment]
As mentioned on that ticket, I think we should drop #1372 for 0.22 and do it 0.23.

**Comment by djc** [comment]
What's your rationale for wanting to push it out to the next release?

**Comment by ctz** [comment]
I think there's some imperative to release 0.22 pretty soon, as PRs we don't really need or want in there are getting closer and/or landing already. I don't want to be keeping back PRs that are otherwise ready, or even worse backing them out, or having multiple trunks, etc.

**Comment by cpu** [comment]
Selfishly I'd also like rustls-ffi to be ready for the 0.22 release as close to the time we cut the release as possible. Refactoring the builders will require another substantial-ish set of changes to https://github.com/rustls/rustls-ffi/pull/341 and getting those ready + reviewed will take more time.

**Comment by djc** [comment]
Removed #1372 from the list.

**Comment by jsha** [comment]
I wanted to look through changes to the public API to make sure we got everything in the draft changelog at https://github.com/rustls/rustls/releases/tag/untagged-725839514beefeccaf57.

I visited the rustdoc for 0.21.9 and latest `main`, went to "All Items", copy-pasted, filtered with `%s/\(.*\)::\([^:]*\)/\2 \1
` to put the type name first and the path last, sorted, and diffed, then manually looked to see whether the differences were mentioned already. Some things I found:

- [BulkAlgorithm](https://docs.rs/rustls/latest/rustls/enum.BulkAlgorithm.html) is removed.
- [BorrowedPlainMessage](https://rustdoc.crud.net/jsha/rustls-doc/rustls/crypto/cipher/struct.BorrowedPlainMessage.html) is new.
  - [OpaqueMessage](https://rustdoc.crud.net/jsha/rustls-doc/rustls/crypto/cipher/struct.OpaqueMessage.html) is elevated from internals to the public API.
- [OkmBlock](https://rustdoc.crud.net/jsha/rustls-doc/rustls/crypto/tls13/struct.OkmBlock.html) is new.
- Many internals types are removed. This probably doesn't need to be mentioned in the changelog since they are already documented as unstable.
- [SignError](https://docs.rs/rustls/latest/rustls/sign/struct.SignError.html) has been moved to two separate `struct SignError`s, one per provider.
- [supported_sign_tls13](https://docs.rs/rustls/latest/rustls/sign/fn.supported_sign_tls13.html) is removed.

SignError is a weird type. It says "Errors while signing", but is only returned by these six functions. In other words, it's used as a parse error, not a signing error.

```
rustls::crypto::aws_lc_rs::sign::any_ecdsa_type
rustls::crypto::ring::sign::any_ecdsa_type
rustls::crypto::aws_lc_rs::sign::any_eddsa_type
rustls::crypto::ring::sign::any_eddsa_type
rustls::crypto::aws_lc_rs::sign::any_supported_type
rustls::crypto::ring::sign::any_supported_type
```

Since we consider the top level namespace to be important, "well paved path" stuff, I thought it would be useful to list all the top level items in particular in this issue to see if they are as expected, and if they require special callouts in the changelog.

## Removed from top level

- ALL_CIPHER_SUITES
- ALL_KX_GROUPS
- BulkAlgorithm
- Certificate
- Constants
- DEFAULT_CIPHER_SUITES
- OwnedTrustAnchor
- PrivateKey
- SupportedKxGroup
- Ticketer

## Added to top level

 - CipherSuiteCommon
 - OtherError
 - TicketSwitcher
 - WebPkiSupportedAlgorithms

I've attached [old.txt](https://github.com/rustls/rustls/files/13431877/old.txt) and [new.txt](https://github.com/rustls/rustls/files/13431878/new.txt) in case you'd like to look at the difference yourself. Note this doesn't get into method signatures, just structs / traits / enums / etc.

**Comment by jsha** [comment]
Here's another view, Moved / Renamed / Added / Removed. As a user of a library I appreciate changelogs that have each modified item listed out explicitly, so when I get a compile error upon migrating, I can quickly check "was this removed outright or do I just need to import it under a different name?"

# Moved

 - ALL_CIPHER_SUITES (crypto providers)
 - ALL_KX_GROUPS (crypto providers)
 - DEFAULT_CIPHER_SUITES (crypto providers)
 - SECP256R1 (crypto::aws_lc_rs::kx_group)
 - SECP384R1 (crypto::ring::kx_group)
 - any_ecdsa_type (crypto providers)
 - any_eddsa_type (crypto providers)
 - any_supported_type (crypto providers)
 - CipherSuiteCommon (top level)
 - ClientCertVerified (server::danger)
 - ClientCertVerifier (server::danger)
 - DangerousClientConfig (client::danger)
 - DnsName (server::danger)
 - HandshakeSignatureValid (client::danger)
 - ServerCertVerified (client::danger)
 - ServerCertVerifier (client::danger)
 - Signer (crypto::signer) -- [possibly a mistake](https://github.com/rustls/rustls/issues/1614)
 - SignError (crypto providers) -- [possibly a mistake](https://github.com/rustls/rustls/issues/1614)
 - SigningKey (crypto::signer) -- [possibly a mistake](https://github.com/rustls/rustls/issues/1614)
 - SupportedKxGroup (crypto)
 - Ticketer (crypto providers)
 - TLS13_AES_128_GCM_SHA256 (crypto providers)
 - TLS13_AES_256_GCM_SHA384 (crypto providers)
 - TLS13_CHACHA20_POLY1305_SHA256 (crypto providers)
 - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (crypto providers)
 - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (crypto providers)
 - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (crypto providers)
 - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (crypto providers)
 - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (crypto providers)
 - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (crypto providers)
 - X25519 (crypto providers)

# Renamed

 - WebPkiVerifier (client::WebPkiServerVerifier)
 - Certificate (rustls_pki_types::CertificateDer)
 - PrivateKey (rustls_pki_types::PrivateKeyDer)

# Added

 - ActiveKeyExchange (crypto)
 - AeadKey (crypto::cipher)
 - Algorithm (quic)
 - ClientCertVerifierBuilder (server)
 - DangerousClientConfigBuilder (client::danger)
 - expand (crypto::tls13)
 - OkmBlock (crypto::tls13)
 - OutputLengthError (crypto::tls13)
 - ServerCertVerifierBuilder (client)
 - TicketSwitcher (top level)
 - WebPkiClientVerifier (server)
 - WebPkiSupportedAlgorithms (top level)

# Added (crypto provider extensibility)

 - RING (crypto::ring)
 - AWS_LC_RS (crypto::aws_lc_rs)
 - HashAlgorithm (crypto::hash)
 - Hash (crypto::hash)
 - Hkdf (crypto::tls13)
 - HkdfExpander (crypto::tls13)
 - HkdfExpanderUsingHmac (crypto::tls13)
 - HkdfUsingHmac (crypto::tls13)
 - Hmac (crypto::hmac)
 - Iv (crypto::cipher)
 - KeyBlockShape (crypto::cipher)
 - Key (crypto::hmac)
 - KeyExchangeAlgorithm (crypto)
 - make_tls12_aad (crypto::cipher)
 - make_tls13_aad (crypto::cipher)
 - MessageDecrypter (crypto::cipher)
 - MessageEncrypter (crypto::cipher)
 - Nonce (crypto::cipher)
 - Nonce (crypto::cipher)
 - OpaqueMessage (crypto::cipher)
 - Output (crypto::hash)
 - PlainMessage (crypto::cipher)
 - Prf (crypto::tls12)
 - PrfUsingHmac (crypto::tls12)
 - SharedSecret (crypto)
 - Tag (crypto::hmac)
 - Tls12AeadAlgorithm (crypto::cipher)
 - UnsupportedOperationError (crypto::cipher)

# Added (error types)

 - GetRandomFailed (crypto)
 - OtherError (top level)
 - UnsupportedOperationError (crypto::cipher)
 - VerifierBuilderError (client)
 - VerifierBuilderError (server)

# Removed

 - AllowAnyAnonymousOrAuthenticatedClient
 - AllowAnyAuthenticatedClient
 - BulkAlgorithm
 - CertificateTransparencyPolicy
 - supported_sign_tls13
 - WantsTransparencyPolicyOrClientCert
 - OwnedTrustAnchor

**Comment by jsha** [comment]
One theme in the upcoming release is that there are several new error types:

GetRandomFailed (crypto)
OtherError (top level)
UnsupportedOperationError (crypto::cipher)
VerifierBuilderError (client)
VerifierBuilderError (server)

[`OtherError was added](https://github.com/rustls/rustls/pull/1575) so that crypto providers can return arbitrary errors and bundle them into a variant of `rustls::Error`.

`GetRandomFailed` and `UnsupportedOperationError` seem to suggest an API direction where crypto providers return more specific error types, and rustls itself is the only source of `rustls::Error`. But `OtherError` seems to run counter to that.

`VerifierBuilderError` in `client` and `server` are specific and are generated from within rustls.

Do we have a philosophy of when we want to use the big `rustls::Error` enum vs when we want to have a specialty error type?

**Comment by djc** [comment]
Release notes: https://github.com/rustls/rustls/releases/tag/v%2F0.22.0.
