### ISSUE TITLE
Breaking change on version 0.21.7

### ISSUE THREAD

**Issue by courvoif** [rustls/rustls#1460]
I have a lib crate, let's call it rustls-utils, that depends on rustls v0.21.2 and a bin crate that depends on rustls-utils and one of its dependencies that also depends on rustls. That worked nicely before but now I have an build error.

I've traced it down to the commit 9d4ac865 which introduces a breaking change on `ClientBuilder::with_root_certificates()`.

The parameter `root_store` went from `anchors::RootCertStore` to `impl Into<Arc<anchors::RootCertStore>>`which breaks compilation if used like this:
```rust
let builder = ClientConfig::builder()
    .with_safe_defaults()
    // Fail to build with 
    // error[E0283]: type annotations needed 
    .with_root_certificates(roots.into())
    .with_no_client_auth();
```

It's not really an issue for me since I'm the maintainer of both my lib and my bin but it could be for others.

**Comment by ctz** [comment]
Mhm, that is painful.

The manual is [pretty non-committal](https://doc.rust-lang.org/cargo/reference/semver.html#minor-generalizing-a-function-to-use-generics-supporting-original-type) about whether this is a breaking or non-breaking change (note that this case does apply, I think, because the only allowed type previously was `RootCertStore`, and `impl Into<Arc<RootCertStore>> for RootCertStore` exists thanks to the blanket impl). But then it does  note that this "can potentially create type inference failures" which contradicts the section being labelled "Minor"? :(

**Comment by cpu** [comment]
Do we want to take any action on this (unfortunate) breakage, or just leave this issue as an informational tombstone and try to better in the future? :sweat:

**Comment by djc** [comment]
I do think this is minor and a decision whether this should be considered breakage depends on how common it is for people to run into type inference failures. In this case, given that it's a pretty commonly used crate and that this was a semver-compatible release (thus relatively speedy uptake) with one bug report I feel like the benefits are probably worth the amount of breakage and I guess I'd do it again.

In general, I feel many people are overinterpreting on semver-compatibility as a holy contract -- I think it is a tool that is of great help in trying to communicate how our libraries change and can break downstream code, but it is by definition impossible (nor desirable) to never change behavior in semver-compatible releases.

So, we're sorry for the inconvience we caused for breaking your crate in a released billed as semver-compatible (rather than breaking it down the line with the release of 0.22), but I don't think we're going to change it back at this point.
