### ISSUE TITLE
Add "ring-compat" feature

### ISSUE THREAD

**Issue by stevefan1999-personal** [rustls/rustls#1490]
With the 0.22 release imminent, we should consider making breaking API change such as:

- ServerConfig::builder() -> ServerConfig::builder_with_ring()
- ClientConfig::builder() -> ClientConfig::builder_with_ring()

All these old ring exclusive function should be redirected to ring counterpart, marked as deprecated, and only provided as a short-term compatibility shim when `ring-compat` feature is enabled, for example:

```rust
impl ServerConfig {
    #[cfg(feature = "ring-compat")]
    /// Create builder to build up the server configuration with the default
    /// `CryptoProvider`.
    ///
    /// For more information, see the [`ConfigBuilder`] documentation.
    #[deprecated(since = "0.22.0", note = "ring is optional since 0.22 and consider using builder_with_ring for clarification")]
    pub fn builder() -> ConfigBuilder<Self, WantsCipherSuites> {
        Self::builder_with_ring()
    }

    #[cfg(feature = "ring")]
    /// Create builder to build up the server configuration with the default
    /// `CryptoProvider`.
    ///
    /// For more information, see the [`ConfigBuilder`] documentation.
    pub fn builder_with_ring() -> ConfigBuilder<Self, WantsCipherSuites> {
        Self::builder_with_provider(crate::crypto::ring::RING)
    }
}
```

## Justification

Many crates out here are using rustls as interdependencies/transitively using rustls, for example:

- axum-server uses hyper-rustls (with default-features)
- hyper-rustls uses rustls and tokio-rustls and have ring feature enabled by default
- tokio-rustls uses rustls and also have ring feature enabled by default
- rustls uses ring out of the box

Therefore, it is highly likely that the developers would just simply strip out the generic as a lazy-but-easy fix, and so ring would still most likely end up in the Cargo supply chain because of that obscure dependency and feature combinations, effectively making the ring optional effort almost useless.

Thus, we should take a more radical approach: break the old API, but also giving the user to restore the behavior using `ring-compat`, as an insurance to make sure it is intentional to use ring exclusively.

**Comment by djc** [comment]
We've been trying to reduce the amount of Cargo features in #1437, and I don't think this is a good enough reason to add one back. The simple "fix" here would be to just require callers to supply a crypto provider unconditionally. Honestly I'm not in favor of that -- I think many downstream users would be happy to let us make the choice for them. I think you'll have to advocate with downstream dependencies to add API to configure an alternative crypto provider. For tokio-rustls and hyper-rustls, that's us, so that should be trivial. Also, many downstream dependencies already allow you to pass in a custom config which you can wire up with whatever crypto provider you like.
