### ISSUE TITLE
x509: heap allocation hotspot in ASN1-wrapping logic

### ISSUE THREAD

**Issue by lucab** [rustls/rustls#1562]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Applicable Version(s)**
A list of versions and platforms you've tested with.

`rustls-0.21.7`

**Describe the bug**

I was analyzing the memory/heap profile of a (non-public) Rust application with https://github.com/KDE/heaptrack, and it highlighted an heap-allocation hotspot coming from the DER-wrapping logic in `rustls`:
https://github.com/rustls/rustls/blob/b776a5778ad333653670c34ff9125d8ae59b6047/rustls/src/x509.rs#L5-L26

Apparently this logic can be reached (in a loop) when building an HTTPS client with `hyper` plus `rustls`, when processing trust anchors, through https://docs.rs/rustls/latest/rustls/struct.OwnedTrustAnchor.html#method.from_subject_spki_name_constraints.

There are a number of byte-prepending calls in that logic which can negatively affect memory allocation patterns.
It may be useful to benchmark it (e.g. against https://docs.rs/webpki-roots/) and try to optimize that.

**Comment by cpu** [comment]
:wave: Hi, thanks for filing an issue. I remember this code coming up in unrelated code review in the past and everyone was pretty unhappy with the current state. I think I even tried refactoring it to build the buffer up backwards to try and reduce the byte-prepending calls but I believe the feature I was working on alongside that change didn't end up landing. It might be worth reviving that effort.

**Comment by cpu** [comment]
> I remember this code coming up in unrelated code review in the past
> ...
> I think I even tried refactoring it to build the buffer up backwards to try and reduce the byte-prepending calls

Aha, it was on a [webpki PR](https://github.com/rustls/webpki/pull/67) and the approach I was playing with [is in this commit](https://github.com/rustls/webpki/commit/fb0cc1424c03b49afc913975e0919e4a79e5be84).

**Comment by jsha** [comment]
I put together a PR at #1563.

If we wanted to do even better than this, we could have WebPkiClientCertVerifier store a `Vec<u8>` of pre-encoded `PayloadU16<DistinguishedName>`, instead of the current `root_hint_subjects: Vec<DistinguishedName>`.

One thing that's a little surprising, though, @lucab: Usually a trust store is built once, wrapped into an `Arc`, and then reused repeatedly. Could it be that your non-public application is re-creating its trust store too often? If it's only created once for the lifetime of the application I wouldn't expect it to be significant for heap profiling.

Also it's possible that the latest (unreleased) main bypasses this problem entirely. The relevant code path is used in building hints for servers to send to clients. Since you're just building a client, that code shouldn't get called. I believe recent unreleased refactorings make that the case.

**Comment by lucab** [comment]
> Usually a trust store is built once, wrapped into an Arc, and then reused repeatedly. Could it be that your non-public application is re-creating its trust store too often? If it's only created once for the lifetime of the application I wouldn't expect it to be significant for heap profiling.

@jsha you are absolutely right, the application was buggy as it was creating new trust stores too often. It has been patched in the meanwhile to cache those better. There was already some (bounded) caching in place, but we found that in this case it wasn't as effective as expected.

I also see now that the code in `main` has been reworked in the meanwhile, so likely this isn't an issue for clients anymore. Though this may still show up if the logic ends up used in a loop somewhere in a busy path, so I think it's a good idea to land https://github.com/rustls/rustls/pull/1563.
