### ISSUE TITLE
Process-level selection of CryptoProvider

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#1642]
Right now, if a `CryptoProvider` is chosen, it's done on a per-config basis (more or less per-connection). That means, if different crates use rustls independently, and they explicitly configure `CryptoProvider`, they may choose different ones. That's non-ideal because it means multiple implementations linked in the final binary. And some of the use cases for `CryptoProvider` are policy ones: an organization may wish to only cryptography it has reviewed; or may be required to only use FIPS cryptography.

I think the status quo is that crates that use rustls should expose a way to pass in a configuration. For instance, HTTP clients and servers; SDK clients that build on top of HTTP clients.

You can imagine three levels at which to set program-level policy about which cryptographic providers to use:

 - Linker level: link only one cryptographic provider. This is how the C world does it, but the additive nature of Cargo features makes it hard to enforce in the Rust world.
 - Config / connection level: users have to know all the places their binary might use rustls, and make sure they pass a correct runtime configuration for them.
 - Process level: the binary is responsible for setting a global value at most once. [This is how the `log` package does it](https://docs.rs/log/latest/log/fn.set_logger.html).
 
Global state is bad, but I'm starting to think it may be a more effective way to set policy for an entire program.
 
Under the status quo, we probably need to document a strong requirement that non-binary crates using rustls must have a way for their callers to pass `ClientConfig` / `ServerConfig`.

**Comment by djc** [comment]
I think it's good to have this discussion, but I still lean towards "global state is still bad and something to be avoided".

Assorted thoughts:

* How to configure the desired crypto provider is one aspect, but auditability of which crypto providers might be used in a given binary is another. I would argue that, as long as it is easy/straightforward to audit which crypto providers are used, it is somewhat less important that the configurability. IMO the cargo-audit tooling and `Cargo.lock` files give us pretty good tools to audit binaries built by Cargo, at least. I suppose it's harder to audit at the symbol level because there are many small functions involved in cipher suites, the API doesn't avoid mixing and matching, etc.

* One challenge with exposing the config types in downstream libraries is that the rustls API is still not very stable, and so public config APIs require semver-incompatible changes which take a long time to trickle downstream. The lack of API stability also makes downstream libraries (rightfully) less inclined to directly expose rustls config types in their API. If we manage to nail the security vs ergonomics of the config builders (and maybe with things like the [restrictions RFC](https://github.com/rust-lang/rfcs/pull/3323)) it becomes more feasible to stabilize at least the configuration API.

* We could help drive Cargo-side improvements like [global features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618).

**Comment by cpu** [comment]
I think this was resolved by #1766.
