### ISSUE TITLE
v0.22 breaks backward compatibility

### ISSUE THREAD

**Issue by daniel-pfeiffer** [rustls/rustls#1690]
**Checklist**
* [x] I've searched the issue tracker for similar bugs.

**Describe the bug**
In v0.21 I could
```rust
let mut root_store = RootCertStore::empty();
root_store.add_parsable_certificates(&[
    b"...".to_vec(),
    b"...".to_vec()]);
```
Now this no longer compiles, wanting `CertificateDer`. A minor version bump shouldn't break things.

Such happenings are probably the reason why `ureq` tends to lock you down to an older version, which is very annoying, because I need to then use the same, to be able to pass my store to it.

**Applicable Version(s)**
v0.21 ok
v0.22 not ok

**Comment by ctz** [comment]
0.21 to 0.22 is a major version change.

**Comment by cpu** [comment]
> A minor version bump shouldn't break things.
...
> 0.21 to 0.22 is a major version change.

I think the confusion here is that you're thinking of our versioning as if Rustls were v1.y.z, but we're following the conventional [Cargo semver](https://doc.rust-lang.org/cargo/reference/semver.html#change-categories) guidelines where:
> releases starting with “0.y.z” can treat changes in “y” as a major release, and “z” as a minor release.

The [0.22.0](https://github.com/rustls/rustls/releases/tag/v%2F0.22.0) changelog details the breaking changes that were made since 0.21, including the change to `RootCertStore` called out here.

The `main` branch of `ureq` has already been updated to accommodate those changes (https://github.com/algesten/ureq/pull/690). You may need to inquire with the `ureq` maintainers to find out when they plan to release a new version with the 0.22 update.

**Comment by daniel-pfeiffer** [comment]
Thanks for the detailed clarification! 🙏🏻
