### ISSUE TITLE
About empty root hints list in "certificate_authorities" extension

### ISSUE THREAD

**Issue by Taowyoo** [rustls/rustls#1727]
**Is your feature request related to a problem? Please describe.**

This change (https://github.com/rustls/rustls/pull/1553/commits/3a4d9e289044c7d601799481ddad67b381ef5a08) in `0.22` cause one compatibility issue with OpenJdk.
The empty root hints list in `certificate_authorities` extension is not accepted by JDK.

It is not compatible with Java's TLS library (which is JSSE, all versions applys), see:
- https://bugs.openjdk.org/browse/JDK-8322509
- https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/ssl/CertificateAuthoritiesExtension.java#L66-L96

And Java's implementation is supported by following words in the RFC https://datatracker.ietf.org/doc/html/rfc8446#section-4.4.2.3:

>    -  If the "certificate_authorities" extension in the
>       CertificateRequest message was present, at least one of the
>       certificates in the certificate chain SHOULD be issued by one of
>       the listed CAs.

I am not mean the implementation in `rustls` is wrong, we just now have a compatibility issue because of the flexible part in the RFC.

**Describe the solution you'd like**

I am wondering is it possible to have a new config field in server side to customize the behavior of sending `certificate_authorities` extension, such as:
- having a boolean to disable `certificate_authorities` extension
- having a boolean to avoid sending  `certificate_authorities` extension when root hints list returned by `ClientCertVerifier` is empty.

**Reproduce**

See my repo: https://github.com/Taowyoo/java-tls13-bug

**Note**

I am also trying to submit a patch on Java side to change their behavior. But at least one side needs change.

**Comment by cpu** [comment]
Interesting, thanks for filing a bug (both here and w/ OpenJDK)!

I'm about to log out for the evening but the change to allow an empty list was motivated by [NIST.SP.800-52r2 3.5.4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf) "Server Hints List" where it says (emphasis mine):

> To mitigate this failure, the server shall either: 1) maintain the trust anchors of the various
> PKIs whose subscribers are the potential clients for the server and include them in the hints list
> or 2) **be configured to send an empty hints list** so that the client can always provide a certificate it
> possesses. The hints list shall be distinct from the server’s trust anchor store.

That citation might be helpful context for the Java folks.

> And Java's implementation is supported by following words in the RFC

Since the RFC language in 8446 4.4.2.3 is a SHOULD I don't think the Java position to consider the extension invalid is supported by the text you're citing. :thinking: 

All that said: I think we added this feature fairly speculatively. If it's causing broad incompatibility with Java it makes sense to revisit! 

> See my repo: https://github.com/Taowyoo/java-tls13-bug

One other question. In this repo you're [explicitly not sending any hints](https://github.com/Taowyoo/java-tls13-bug/blob/97363338a44a997f6239c8dbc5365f053bf69a60/rust-server-example/src/main.rs#L104-L106). Wouldn't it be appropriate in this circumstance to be doing what the webpki verifier does by default and [populating the hints](https://github.com/rustls/rustls/blob/b3913a5ac2ecc4d3daea3c4259c84bfeceb749f6/rustls/src/webpki/client_verifier.rs#L44) based on the trust store you use to verify client certificates?

It sounds like the incompatibility is specific to avoiding sending any hints and so I'm hoping you can help explain the motivation for that choice since it's not the default for Rustls own verifier implementations (and apparently causes compatibility issues :laughing: )

**Comment by cpu** [comment]
> Wouldn't it be appropriate in this circumstance to be doing what the webpki verifier does by default and [populating the hints](https://github.com/rustls/rustls/blob/b3913a5ac2ecc4d3daea3c4259c84bfeceb749f6/rustls/src/webpki/client_verifier.rs#L44) based on the trust store you use to verify client certificates?
...
> It sounds like the incompatibility is specific to avoiding sending any hints and so I'm hoping you can help explain the motivation for that choice

Maybe this is something like a (dangerous) configuration where any client certificate is accepted unconditionally and there are no trust anchors in play?

**Comment by Taowyoo** [comment]
> I'm about to log out for the evening but the change to allow an empty list was motivated by [NIST.SP.800-52r2 3.5.4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf) "Server Hints List" where it says (emphasis mine):

Yes! This will help a lot when try to convince Java folks to accept the change.

> Since the RFC language in 8446 4.4.2.3 is a SHOULD I don't think the Java position to consider the extension invalid is supported by the text you're citing. 🤔

Thank you for explaining the meaning of SHOULD.

> It sounds like the incompatibility is specific to avoiding sending any hints and so I'm hoping you can help explain the motivation for that choice since it's not the default for Rustls own verifier implementations (and apparently causes compatibility issues 😆 )

The use case is exactly same as your words in original commit: 

> In some circumstances the server may want the client to send whatever
> client certificate it has on hand with no help from the server hints to
> decide which will be appropriate.

Our use case is checking peer's certificate with special extension based on SNI.

**Comment by ctz** [comment]
I think we're in the wrong here. I think this text from NIST:

> To mitigate this failure, the server shall either: 1) maintain the trust anchors of the various
PKIs whose subscribers are the potential clients for the server and include them in the hints list
or 2) be configured to send an empty hints list (...)

Is talking only in terms of TLS1.2, where `certificate_authorities` is required to be present by the encoding, but can be empty:

```text
      struct {
          ClientCertificateType certificate_types<1..2^8-1>;
          SignatureAndHashAlgorithm
            supported_signature_algorithms<2^16-1>;
          DistinguishedName certificate_authorities<0..2^16-1>;
      } CertificateRequest;
```

However, in TLS1.3 it is in an extension which is defined:

```text
      opaque DistinguishedName<1..2^16-1>;

      struct {
          DistinguishedName authorities<3..2^16-1>;
      } CertificateAuthoritiesExtension;
```

(the 1 in `DistinguishedName` means it should be non-empty, the 3 in `authorities` means at least one entry.)

Will do a PR to fix this shortly.

**Comment by cpu** [comment]
Ahhh! Yes ok, I'm swayed by that argument :+1: Thanks @ctz
