### ISSUE TITLE
Make `ring` the default again

### ISSUE THREAD

**Issue by praveenperera** [rustls/rustls#2116]
I've never had any troubles with `ring` but the `aws-lc` library needs to be finessed to work in GitHub actions: https://github.com/avencera/rustywind/actions/runs/10760933878/job/29839537060

And doesn't work at all in iOS and android: https://github.com/bitcoindevkit/rust-electrum-client/pull/135

Why switch something that wasn't broken, and worse yet why make the new default LESS compatible?

**Comment by djc** [comment]
There is extensive discussion in #1913. Feel free to comment there after you've read the existing discussion and feel you have something new to point out.

**Comment by scalpel4k** [comment]
Please reconsider your decision!

Making aws-lc the default backend completely ignores the reality. aws-lc can't easily be installed on most (Linux) systems let alone only few distributions even ship at least devel packages for it. I guess I don't have to explain that OpenSSL (which IS the default out there) and aws-lc can't easily coexist, and one isn't a replacement for the other either.

So this puts you into a trap position, also in container workloads! There's not even a solution for Alpine let alone Debian. In Alpine they've tried it for the edge branch, but you can't even install some cargo plugins. Am I supposed to start patching cargo plugins just because I need some crate with SSL support?

The reality is that you have to wiggle out of this aws-lc dependency somehow if you don't wanna invest tons of time to make aws-lc work on your system of choice (or non-choice!).
Unfortunately many crate authors don't even care (or know) that there are different crypto backends. So sooner or later you'll hit a dependency that pulls in aws-lc again!

I've read #1913 and locking the discussion isn't solving the issue, neither is putting the egg in other's basket. How about that, make aws-lc the default if cargo has this global feature thing you're referring to, but please not before.

thx for your time
