### ISSUE TITLE
Feature flag to automatically use webpki-roots?

### ISSUE THREAD

**Issue by joshtriplett** [rustls/rustls#709]
rustls requires using a matching version of webpki-roots that uses the same webpki types. Numerous library crates that build on rustls often have feature flags to enable one or both of rustls-native-certs or webpki-roots, and then do the same code sequence to add those roots to the rustls client config. Users of those library crates in turn need to request such features, and then enable them in the library crate.

Would it potentially be reasonable to add a feature flag to rustls, which when set, causes rustls to automatically add webpki-roots to the client config? That would allow numerous library crates building on rustls to drop their code doing so, and prevent many more such library crates from needing to add their own options for that. Instead, users of such library crates can just enable the appropriate feature flag in rustls to get the behavior they want.

**Comment by djc** [comment]
For webpki, webpki-roots and rustls-native certs, since they are already semver-locked together, I think it would be useful to add re-exports of those crates based no a configuration. We could perhaps add methods to the new config builders that then leverages this support directly, but I don't think we should set the root cert store implicitly based on a feature flags, since this tends to have surprising effects due to the additivity constraints of Cargo features (as in https://github.com/rustls/hyper-rustls/pull/134).

**Comment by joshtriplett** [comment]
In practice, just about every crate in the ecosystem is already doing that: either using webpki-roots or rustls-native-certs or offering a choice between the two.

**Comment by djc** [comment]
@briansmith until there is a viable alternative (that is not an upgrade to webpki-roots or rustls-native-certs), it's not clear to me that it makes sense to make these options harder to use than necessary. Do you have reasons to assume the issues with webpki-roots and rustls-native-certs cannot be fixed in the respective crates?

**Comment by briansmith** [comment]
> Do you have reasons to assume the issues with webpki-roots and rustls-native-certs cannot be fixed in the respective crates?

Yes. Give me a couple of weeks and I'll share why in detail.

**Comment by jsha** [comment]
I wrote up my understanding of some of the issues here: https://github.com/rustls/rustls-native-certs/issues/25. Summary: "In general, root programs maintain both a trust store and a platform verifier, and the behavior of the two is linked. Distrusts may be implemented first in the verifier (subject to various conditions), and only much later by removal from the trust store."

**Comment by briansmith** [comment]
@jsha That is an excellent summary, and the thinking there has driven the changes I've already made to the certificate validation APIs in Rustls, so that the right native integration can be implemented.

**Comment by joshtriplett** [comment]
Ah! That makes sense. Would that help cover cases where the certificate store needs an explicit negative entry for a CA or sub-CA?

**Comment by jsha** [comment]
> Would that also help cover cases where the certificate store needs an explicit negative entry for a CA or sub-CA, or a "must use CT" entry?

Presumably yes. By the way, worth mentioning that "must use CT" is no longer a great example, because "must use CT" is now enforced as a blanket policy in Chrome (and Apple devices), rather than something enforced for a subset of CAs.

https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/QphQiDwBlC8/m/MdRiOy_qBgAJ

**Comment by briansmith** [comment]
I think we should close this. I filed https://github.com/rustls/rustls/issues/940 to document why we can't do things like this.

**Comment by bdaehlie** [comment]
Closing on the basis of Brian's last comment.

**Comment by djc** [comment]
I completely agree that a Cargo feature flag, by itself, is tricky because of the additive nature of Cargo features. However, a proven concept is to offer a Cargo feature that can only be used/enabled by an explicit API call. For example, in this case, we could offer `with_webpki_roots()` and `with_native_roots()` and maybe `with_platform_verifier()` as an alternative to the `with_root_certificates()` API. This would make life quite a bit easier for downstream users without the risks of just a Cargo feature.

Personally I think this would be an improvement, as currently the conversions required to do any of the above manually are kinda annoying to write out (there's a bunch of boilerplate that's duplicated across a whole lot of low-level crates).

**Comment by ctz** [comment]
On these two points:

> rustls requires using a matching version of webpki-roots that uses the same webpki types.
- and -
> Personally I think this would be an improvement, as currently the conversions required to do any of the above manually are kinda annoying to write out (there's a bunch of boilerplate that's duplicated across a whole lot of low-level crates).

We introduced and stablised the rustls-pki-types crate since which solved this versioning hazard and much of the boilerplate involved.

> Numerous library crates that build on rustls often have feature flags to enable one or both of rustls-native-certs or webpki-roots,

Nowadays we also have [rustls-platform-verifier](https://github.com/rustls/rustls-platform-verifier) which (I think) addresses ([and discusses at length](https://github.com/rustls/rustls-platform-verifier?tab=readme-ov-file#deployment-considerations)) the issues discussed earlier in this ticket.

I think we'd like to promote that as the most preferable way for general-purpose clients to verify certificates in the WebPKI for rustls. I think right now adding a crate feature just for webpki-roots takes the ecosystem in the wrong direction, because having a similar crate feature for rustls-platform-verifier is not possible (it depends on rustls).

So I am somewhat minded to close this. Thoughts?

**Comment by joshtriplett** [comment]
I appreciate that the "matching version of webpki-roots" problem has been solved; that'll make various callers easier to maintain.

The underlying problem I'm trying to solve here is that it's currently difficult to have rustls certificate handling policy under the control of the *application*, rather than using the defaults of various libraries invoking rustls. Having libraries give control of certificate policy to applications requires a lot of plumbing for each library, which the application then needs to consistently invoke for each library. It would be nice if there were a convenient "default certificate policy" that an application could configure in rustls, and that was the *obvious default choice* for libraries to use if not otherwise configured. That way, an application could configure this *once* and expect libraries to always respect it.

Among the policies different applications want:

- Pin a certificate and allow only that certificate; connections to servers with other certificates won't happen at all.
- Pin a certificate for connections to a particular domain, but use another policy for connections to other domains.
- Assume that the system certificate store doesn't exist (e.g. because they're running in a minimal/container/etc environment), and don't even bother looking for it because that adds to startup time.
- Default to not including the system certificate store, and require an explicit command-line option or configuration option to opt in, to help users be aware of the implications of unexpected certificates in their system certificate store.
- Fall back to the system certificate store but set a process-wide flag when doing so, to allow for displaying a warning for user awareness.

**Comment by djc** [comment]
I think our current take is that the language tooling should solve this, as in https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618.

**Comment by joshtriplett** [comment]
@djc No argument that that would be better; the question is whether to wait for that feature to exist, which might be a while.

**Comment by djc** [comment]
Do you think #1821 would fulfill your use case?

**Comment by joshtriplett** [comment]
@djc Yes, completely.

**Comment by djc** [comment]
Closing this in favor #1821, then.
