### ISSUE TITLE
ClientConfig and ServerConfig vs Builders

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#758]
In the latest master, ClientConfig and ServerConfig no longer have a `new()`. There are new Builder types to construct them, but someone attempting to port old code without many changes might be tempted to try and instantiated a ClientConfig or ServerConfig by setting all of their fields. That's currently impossible, because `verifier` on both types is private.

Is that an intentional choice, to prevent construction of ClientConfig and ServerConfig without going through the Builders? If so, we should document it on the respective structs. Also if that's the case: should all the other fields be made private, if the intent is only to support construction via Builder?

**Comment by jsha** [comment]
FWIW, it would be quite convenient for crustls' purposes if `verifier` were public; that would allow it to maintain more or less the builder API it currently has, at least for now.

**Comment by djc** [comment]
IMO we should keep the `verifier` field private, and probably also make the `cipher_suites`, `kx_groups` and `versions` fields private (since these are also set through the builder API). If we don't, the validation we do as part of the builder construction becomes somewhat useless. Also keeping the legacy config construction API working in rustls-ffi doesn't seem like great justification for this by itself?

**Comment by ctz** [comment]
Yes, `verifier` should be kept private really. I wonder if the error would be better if we set these structs as `non_exhaustive`?

If you think it's useful, I wouldn't be strongly opposed to introducing `new()` on these types, with the following body (from the docs):

```
ConfigBuilder::with_safe_defaults()
    .for_server()
    .unwrap();
```

**Comment by jsha** [comment]
I think mainly what's needed is a sentence in the documentation for ServerConfig and ClientConfig that says "these cannot be constructed manually; you must use ConfigBuilder to create one."

In terms of consistency of the API, it's odd that a user is allowed to modify post-hoc any field of a ServerConfig or a ClientConfig, _except_ verifier. The issue of gating behind dangerous_configation makes sense - but what about a `set_verifier` method that is only present under dangerous_configuration?

**Comment by briansmith** [comment]
I agree with making all of the fields private in general. If there are any that need to be public, let's hear the reasoning for each one on a case-by-case basis and try to find alternate solutions.

I think making all the fields private will help make the API less confusing.

**Comment by djc** [comment]
It looks like making all the (builder-specified) fields private will make things that `bogo_shim` and the tests need to do a bunch harder, though:

https://github.com/ctz/rustls/blob/main/rustls/examples/internal/bogo_shim.rs#L370

**Comment by jsha** [comment]
What about making them `#[doc(hidden)]`? Or make `ServerConfig` a wrapper of `ServerConfigInternal`, and make the latter `#[doc(hidden)]`?

**Comment by briansmith** [comment]
> It looks like making all the (builder-specified) fields private will make things that bogo_shim and the tests need to do a bunch harder, though:
> 
> https://github.com/ctz/rustls/blob/main/rustls/examples/internal/bogo_shim.rs#L370

I think that if it is difficult or impossible to rewrite that part of bogo_shim to use the official API for what it is trying to do, then it is going to be difficult or impossible for real applications to do what they need too.

I'm a big believer that integration and functional tests should use the public/official API as much as possible, so I think it's worth trying to figure out how to change bogo_shim and other tests to use the official APIs.

I suggest we take a few of the tests, or a few sections of test infrastructure, and try to rewrite them using the builder API as it is intended to be used, and then reevaluate.

> What about making them #[doc(hidden)]? Or make ServerConfig a wrapper of ServerConfigInternal, and make the latter #[doc(hidden)]?

Only some users use the rustdoc documentation. I think a lot of people discover the API using their IDE in a way that wouldn't let them see that those things aren't intended to be used, e.g. using autocomplete.

**Comment by briansmith** [comment]
> It looks like making all the (builder-specified) fields private will make things that `bogo_shim` and the tests need to do a bunch harder, though:
> 
> https://github.com/ctz/rustls/blob/main/rustls/examples/internal/bogo_shim.rs#L370

That code fragment is saying "sometimes I want to use the default cert resolver; sometimes I want to use a custom cert resolver." I have to admit it is far from obvious how the API intends to support that kind of dynamic choice--especially when there are many such dynamic choices. We might need @ctz to explain.

This also reinforced my belief that we should try to rewrite the testing stuff using the normal API, to identify such problematic cases.

**Comment by djc** [comment]
> This also reinforced my belief that we should try to rewrite the testing stuff using the normal API, to identify such problematic cases.

Agreed, I already started on that, which is when I ran into this case.

**Comment by briansmith** [comment]
@olix0r @hawkw I think it would be a good idea for you to do a PoC of redoing your TLS code using the new Rustls API (on Rustls main branch) to make sure the new configuration API can actually do what you need before it gets fossilized.

@complexspaces I know you have some non-trivial configuration logic for TLS as well. It would be good to verify that the new API supports your needs before the API is frozen.

**Comment by djc** [comment]
(Note: this is in the context of preparing the 0.20 release.) @ctz maybe it's useful to actually publish a 0.20.0-beta.1 to crates.io?

**Comment by complexspaces** [comment]
Thanks for the heads up, @briansmith.

I switched my crate over to using rustls's `main` branch and didn't have much trouble at all migrating to the new APIs, and everything seems to be working as expected still. However, I did run into a few usability bumps:
- `WebPkiOp::ParseEndEntity` seems too specific. Can there also be a parse variant for intermediate certificates, or even better, a generic `ParseCertificate` variant? 
- `ServerName` seems less-than-ideal in the context of certificate verification due to the `#[non_exhaustive]` marker: 
```rust
let name = match server_name {
      rustls::ServerName::DnsName(n) => n.as_ref(),
      _ => return Err(Error::WebPkiError(WebPkiError::CertNotValidForName, WebPkiOp::ValidateForDnsName))
};
```
Can Rustls provide a method that always returns the DNS name? If not, what is the expected way to error out when more variants than `DnsName` exist?

**Comment by jsha** [comment]
One thing that makes the current API feel unfriendly to me: The type names don't really indicate anything meaningful about what state of the config build you are in; they are named after the last thing that you happened to add. So for instance, if you're looking at the docs for [ServerConfigBuilderWithClientAuth](https://hoffman-andrews.com/rustls/rustls/struct.ServerConfigBuilderWithClientAuth.html), and the methods are:

```
with_single_cert
with_single_cert_with_ocsp_and_sct
with_cert_resolver
```

It's not really clear why those methods are on the "...WithClientAuth" type rather than some other type. Also, if you're searching the docs trying to find the struct that allows you to configure a server cert, it would be surprising to find it under "...WithClientAuth." Also, there are a few types that stand out because they have shorter names: `ConfigBuilder`, `ServerConfigBuilder`, and `ClientConfigBuilder`. I would generally expect those to be more important types - for instance terminal or near-terminal states. But in fact they are unremarkable points in the state machine, where you still need to add more info.

I propose changing the naming scheme to "Wants" instead of "With." That way there will be a clear connection between the type name and the methods on that type. For instance:

```
WantsCipherSuites
  with_safe_defaults()
  with_cipher_suites(...) -> WantsKxGroups
  with_safe_default_cipher_suites(...) -> WantsKxGroups

WantsKxGroups
  with_kx_groups(...) -> WantsVersions
  with_safe_default_kx_groups(...) -> WantsVersions

WantsVersions
  with_safe_default_protocol_versions() -> WantsPeerType
  with_protocol_versions(...) -> WantsPeerType

WantsPeerType
  for_client() -> WantsServerVerifier
  for_server() -> WantsClientVerifier

// After for_client():

WantsServerVerifier
  with_root_certificates(...) -> WantsClientCert
  with_custom_certificate_verifier(...) -> WantsClientCert

WantsClientCert
  with_single_cert(...) -> ClientConfig
  with_no_cert(...) -> ClientConfig

// After for_server():

WantsClientVerifier
  with_client_cert_verifier(...) -> WantsServerCert
  with_no_client_verification(...) -> WantsServerCert

WantsServerCert
  with_single_cert(...) -> ServerConfig
  with_single_cert_with_ocsp_and_sct(...) -> ServerConfig
  with_cert_resolver(...) -> ServerConfig
```

**Comment by djc** [comment]
Another idea: we could flatten the  shared phases of the config builder to use a single type. Since for_client() and for_server() are fallible anyway, we can check that all of the cipher suites, kx groups and versions have been correctly configured at that time.

**Comment by ctz** [comment]
One of the aims here is to check that everything has been done at compile-time rather than runtime.

**Comment by djc** [comment]
Yeah, I do agree that the current compile-time clarity is more desirable.

**Comment by briansmith** [comment]
> Thanks for the heads up, @briansmith.
> * `WebPkiOp::ParseEndEntity` seems too specific. Can there also be a parse variant for intermediate certificates, or even better, a generic `ParseCertificate` variant?

Rustls doesn't parse the intermediates, that's why there's no such error.

> * `ServerName` seems less-than-ideal in the context of certificate verification due to the `#[non_exhaustive]` marker:
> 
> ```rust
> let name = match server_name {
>       rustls::ServerName::DnsName(n) => n.as_ref(),
>       _ => return Err(Error::WebPkiError(WebPkiError::CertNotValidForName, WebPkiOp::ValidateForDnsName))
> };
> ```
> 
> Can Rustls provide a method that always returns the DNS name?

In the near future there will be an IpAddress variant. In the longer term there might be other kinds of names supported.

> If not, what is the expected way to error out when more variants than `DnsName` exist?

I guess it would be good to add an `UnsupportedNameType` for the certificate verification callbacks to return. If you agree, could you file an issue or PR?

**Comment by briansmith** [comment]
Regarding the issue we ran into with the BSSL shim, it seems like at least for the resolver, some implementations will want a way to create the default resolver and then wrap it with their own implementation that might forward some methods to the default resolver.

This makes me think that the API should change so that there is a `create_default_resolver` method. And, maybe this pattern should also be applied to the other extension points (certificate verifier when dangerous configuration is enabled, etc.)

**Comment by djc** [comment]
Another issue I see that `ConfigBuilder::with_safe_defaults()` requires unwrapping for no good reason. Maybe we should have `for_client_with_safe_defaults()` (or something a little more concise) to skip straight to `ClientConfigBuilder`.

**Comment by ctz** [comment]
> Another issue I see that `ConfigBuilder::with_safe_defaults()` requires unwrapping for no good reason.

I addressed this in 3a0757638

**Comment by jsha** [comment]
One other small issue: The documentation for the builders emphasizes the "linker-friendly" aspect, but my current understanding is that the builder pattern serves two purposes: for cipher suites, kx groups, and TLS versions, it allows dead code elimination (linker-friendly), while for validation strategy and certificate provider, it ensures that the user makes a decision about some aspect of configuration that can't be safely defaulted. It would be useful to mention both of these reasons.

**Comment by hawkw** [comment]
In order to test this out in Linkerd, we first had to update `tokio-rustls` to the new APIs. I've opened a draft PR tokio-rs/tls#64, in case anyone's interested in that change.

I did notice a few things while working on this change that should maybe be mentioned:
* Using type state in the config builder APIs to restrict the state transitions to valid ones is a good idea. However, the current state of the API is somewhat difficult to use. In particular, because the config builders are split across a number of distinct types which each have one or two methods, it's difficult to navigate the documentation to see which methods are available.

  One potential improvement would be to have a `ConfigBuilder` type which is _parameterized_ over a typestate type variable. For example, rather than 
  ```rust
  pub struct ConfigWantsVersions {
      // ...
  }
  
  impl ConfigWantsVersions {
      pub fn with_safe_default_protocol_versions(self) -> ConfigWantsPeerType {
          // ...
      }
  
      pub fn with_protocol_versions(
          self,
          versions: &[&'static versions::SupportedProtocolVersion],
      ) -> ConfigWantsPeerType {
          // ...
      }
  }
  
  pub struct ConfigWantsPeerType {
      // ...
  }
  
  impl ConfigWantsPeerType {
      pub fn for_client(self) -> Result<ConfigWantsServerVerifier, Error> {
          // ...
      }
  
      pub fn for_server(self) -> Result<ConfigWantsClientVerifier, Error> {
          // ...
      }
  }
  
  // ...
  
  ```
  we could instead have something like this:
  ```rust
  pub struct ConfigBuilder<State> {
      state: State,
      // ...
  }
  
  impl ConfigBuilder<WantsVersions> {
      pub fn with_safe_default_protocol_versions(self) -> ConfigBuilder<WantsPeerType> {
          // ...
      }
  
      pub fn with_protocol_versions(
          self,
          versions: &[&'static versions::SupportedProtocolVersion],
      ) -> ConfigBuilder<WantsPeerType> {
          // ...
      }
  }
  
  impl ConfigBuilder<WantsPeerType> {
      pub fn for_client(self) -> Result<ConfigBuilder<WantsServerVerifier>, Error> {
          // ...
      }
  
      pub fn for_server(self) -> Result<ConfigBuilder<WantsServerVerifier>, Error> {
          // ...
      }
  }
  
  // ...
  
  ```
  
  That would give us one type which would have a single documentation page listing
  all the methods and state types, which I think would be much easier for users to
  navigate. It would also give us a place to put any methods that are not
  inherently stateful --- they could go on a generic `impl<S> ConfigBuilder<S>`.
  This might improve ergonomics a bit.

* Using the `RootCertStore` type to parse trust anchors from a .pem file (which
seems like a fairly common task) now requires significantly more boilerplate
code. For example, see this diff snippet from `tokio-rustls`'s tests:
  ```diff
    @@ -102,12 +108,19 @@ async fn pass() -> io::Result<()> {
       use std::time::*;
       tokio::time::sleep(Duration::from_secs(1)).await;
  
  -    let mut config = ClientConfig::new();
  -    let mut chain = BufReader::new(Cursor::new(chain));
  -    config.root_store.add_pem_file(&mut chain).unwrap();
  +    let chain = certs(&mut std::io::Cursor::new(*chain)).unwrap();
  +    let trust_anchors = chain
  +        .iter()
  +        .map(|cert| webpki::TrustAnchor::try_from_cert_der(&cert[..]).unwrap())
  +        .collect::<Vec<_>>();
  +    let mut root_store = rustls::RootCertStore::empty();
  +    root_store.add_server_trust_anchors(trust_anchors.iter());
  +    let config = rustls::client_config_builder_with_safe_defaults()
  +        .with_root_certificates(root_store, &[])
  +        .with_no_client_auth();
       let config = Arc::new(config);
  ```
* Similarly, using cerver certs from a `.pem` file also requires more
boilerplate now, as in this diff:
  ```diff
  @@ -13,18 +14,23 @@ use tokio::runtime;
   use tokio_rustls::{TlsAcceptor, TlsConnector};
  
   const CERT: &str = include_str!("end.cert");
  -const CHAIN: &str = include_str!("end.chain");
  +const CHAIN: &[u8] = include_bytes!("end.chain");
   const RSA: &str = include_str!("end.rsa");
  
   lazy_static! {
  -    static ref TEST_SERVER: (SocketAddr, &'static str, &'static str) = {
  -        let cert = certs(&mut BufReader::new(Cursor::new(CERT))).unwrap();
  +    static ref TEST_SERVER: (SocketAddr, &'static str, &'static [u8]) = {
  +        let cert = certs(&mut BufReader::new(Cursor::new(CERT)))
  +            .unwrap()
  +            .drain(..)
  +            .map(rustls::Certificate)
  +            .collect();
           let mut keys = rsa_private_keys(&mut BufReader::new(Cursor::new(RSA))).unwrap();
  +        let mut keys = keys.drain(..).map(rustls::PrivateKey);
  
  -        let mut config = ServerConfig::new(rustls::NoClientAuth::new());
  -        config
  -            .set_single_cert(cert, keys.pop().unwrap())
  -            .expect("invalid key or certificate");
  +        let config = rustls::server_config_builder_with_safe_defaults()
  +            .with_no_client_auth()
  +            .with_single_cert(cert, keys.next().unwrap())
  +            .unwrap();
           let acceptor = TlsAcceptor::from(Arc::new(config));
  
           let (send, recv) = channel();
  ```
  It would be nice if there was a helper method for encapsulating this kind of
  thing.
  
* Rustls provides `Certificate` and `PrivateKey` newtypes that represent
certificates and private keys; but these newtypes can be publicly constructed
from any arbitrary `Vec<u8>`. I would have expected the newtypes to represent
some bytes that have been successfully parsed as a certificate/private key and
that we _know_ to be valid. But, there's currently no way to parse certificates
or private keys and get those types; instead, because PEM file parsing has been
split out to the `rustls-pemfile` crate, it's necessary to parse the certs/keys,
getting back a `Vec<u8>` and then manually wrap them in the appropriate newtype.
This, to me, seems to kind of defeat the purpose of having these newtypes --- I
would expect them to represent a type-level distinction between "some arbitrary
bytes" and known-valid key material.

  It might be worth having tighter integration between `rustls` and
  `rustls-pemfile`...even though it was split out, perhaps some additional APIs
  could be exposed via a feature flagged dependency?

Hopefully this feedback is useful --- my next step is to actually use the new
APIs in the Linkerd proxy, so I'll report back with my experiences there.

**Comment by djc** [comment]
This is great feedback! #771 already moves in the direction of making the builder more typestatey, I'll see if I can implement your suggestion soon.

As for the boilerplate bridging between rustls-pemfile and rustls, as long as we're aiming for neither crate to have a dependency on the other, it'll be hard to bridge the gap. I forget the exact reasoning why it was originally split out...

I agree the newtype wrappers are mostly there as a hint for the humans at this point, which is somewhat useful but not greatly so. Again this depends on how we want to structure cross-crate dependencies.

**Comment by hawkw** [comment]
> This is great feedback! #771 already moves in the direction of making the builder more typestatey, I'll see if I can implement your suggestion soon.

Oh, fantastic --- looks like we were thinking in the same direction! :)

> As for the boilerplate bridging between rustls-pemfile and rustls, as long as we're aiming for neither crate to have a dependency on the other, it'll be hard to bridge the gap. I forget the exact reasoning why it was originally split out...
> 
> I agree the newtype wrappers are mostly there as a hint for the humans at this point, which is somewhat useful but not greatly so. Again this depends on how we want to structure cross-crate dependencies.

One option --- maybe the most obvious one --- is having an optional dependency on `rustls-pemfile` in rustls, which enables some convenience impls. It could be off by default. Another thought, which might be a bit of a bigger change, is splitting out what's currently `rustls` into a new crate (`rustls-tls`, maybe?), and then having a `rustls` which reexports `rustls-tls` and `rustls-pemfile` along with convenience functions that include functionality from both crates?

**Comment by djc** [comment]
Thinking about this some more, maybe the right path forward would be to drop the `Certificate` and `PrivateKey` types, potentially along with a `TrustAnchor` and/or `OwnedTrustAnchor` type into a smaller crate, rustls-types or maybe webpki-types. That seems like it would have few if any incompatible changes even in the longer term, and it would allow rustls, rustls-pemfile, rustls-native-certs and potentially webpki to interoperate using the same base types.

**Comment by briansmith** [comment]
> Thinking about this some more, maybe the right path forward would be to drop the `Certificate` and `PrivateKey` types, potentially along with a `TrustAnchor` and/or `OwnedTrustAnchor` type into a smaller crate, rustls-types or maybe webpki-types. That seems like it would have few if any incompatible changes even in the longer term, and it would allow rustls, rustls-pemfile, rustls-native-certs and potentially webpki to interoperate using the same base types.

I don't see the need or the advantage of doing that right now. The inconvenience mentioned above makes the code a bit less pretty but all of these things are separate for a reason.

A simpler way of addressing some of the feedback about `Certificate` and whatnot would be to rename them to `UnparsedCertificate` and similar. That would be somewhat clearer that those types don't represent "valid" things but are rather mostly used to make sure you don't the arguments to functions in the wrong order.

**Comment by hawkw** [comment]
> I don't see the need or the advantage of doing that right now. The inconvenience mentioned above makes the code a bit less pretty but all of these things are separate for a reason.

I think there's more to it than just being concise --- it would be good to be able to provide users who are not deeply versed in TLS domain knowledge a way to do operations like "use this PEM file as trust anchors" that does the safe, correct thing in most use cases, rather than creating opportunities to do something wrong by mistake.

> A simpler way of addressing some of the feedback about `Certificate` and whatnot would be to rename them to `UnparsedCertificate` and similar. That would be somewhat clearer that those types don't represent "valid" things but are rather mostly used to make sure you don't the arguments to functions in the wrong order.

This seems like a good call if we don't make more significant API changes! :+1:

**Comment by djc** [comment]
#771 now rewrites the builders completely to use type states, I think this makes it much easier to understand what's going on, by reading the documentation for the new `ConfigBuilder` type.

**Comment by hawkw** [comment]
On the subject of sharing types between `rustls`, `webpki`, and other crates, and newtyping parsed certs: cI notice that `webpki`'s `DnsName` was removed from `rustls`' public API in favor of `rustls` defining its own `ServerName` type, but `webpki::TrustAnchor` is still used in `rustls` APIs. `TrustAnchor` has `try_from_xxx` constructors that only return a `TrustAnchors` if a trust anchor was successfully parsed and validated. Meanwhile, `rustls` defines its own `PrivateKey` and `Certificate`, which as mentioned earlier, represent _unparsed_ key material that may or may not be valid. I wonder what could be done to make this interface a little more consistent?

This discussion may be a bit off topic from the original issue here, though. :)

**Comment by djc** [comment]
> I don't see the need or the advantage of doing that right now.

One advantage that I see is that one remaining point of webpki types leaking into rustls API is the webpki `TrustAnchor` type. It looks like the definition of this type has been stable over time, from 0.1.1 (Aug 2016) to 0.22 (Apr 2021). If that type lived in a separate crate with other highly stable type definitions, we would have an integration point between webpki and rustls that would not impose any constraints on either crate's other API evolution. If we moved `UnparsedCertificate` and `UnparsedPrivateKey` in there, that would also help integrations with things like `rustls-native-certs`, `rustsls-pemfile` and even things like Quinn (which currently defines its own `Certificate` and `PrivateKey` wrappers).

**Comment by briansmith** [comment]
> One advantage that I see is that one remaining point of webpki types leaking into rustls API is the webpki `TrustAnchor` type.

The `TrustAnchor` type will change in future webpki releases. I think it makes sense for Rustls to define its own `TrustAnchor` type. That type will likely evolve in similar ways to the webpki version over time, but at least it would be able to do so at its own pace.

**Comment by djc** [comment]
> all of these things are separate for a reason.

Would you mind explaining this in more detail? It seems to me that if (for example), rustls is the major downstream user of webpki, some things would be lot easier if we just merged webpki and rustls outright. It's not all that obvious to me why it's useful for these to be separate.

**Comment by briansmith** [comment]
> > all of these things are separate for a reason.
> 
> Would you mind explaining this in more detail? It seems to me that if (for example), rustls is the major downstream user of webpki, some things would be lot easier if we just merged webpki and rustls outright. It's not all that obvious to me why it's useful for these to be separate.

1. Rustls isn't the only TLS implementation, and the scope of the webpki crate also goes beyond certificate use during the establishment of TLS connections.
2. I plan to extend and otherwise change the definition of `webpki::TrustAnchor` in incompatible ways in the next version of `webpki`.
3. It seems like Rustls API is going to be hard to change in breaking ways in the future. webpki and *ring* will have more flexibility in how we make breaking changes.

I filed PR #780 to address the fact that `webpki::TrustAnchor` is in the Rustls public API.

**Comment by djc** [comment]
I'm going to optimistically close this on the notion that we covered most of the initial concerns (and, in fact, a lot of the subsequent concerns raised in this issue). If there are still improvements to be made, please file a separate issue.

**Comment by kvinsu** [comment]
> > Thanks for the heads up, @briansmith.
> > 
> > * `WebPkiOp::ParseEndEntity` seems too specific. Can there also be a parse variant for intermediate certificates, or even better, a generic `ParseCertificate` variant?
> 
> Rustls doesn't parse the intermediates, that's why there's no such error.
> 
> > * `ServerName` seems less-than-ideal in the context of certificate verification due to the `#[non_exhaustive]` marker:
> > 
> > ```rust
> > let name = match server_name {
> >       rustls::ServerName::DnsName(n) => n.as_ref(),
> >       _ => return Err(Error::WebPkiError(WebPkiError::CertNotValidForName, WebPkiOp::ValidateForDnsName))
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can Rustls provide a method that always returns the DNS name?
> 
> In the near future there will be an IpAddress variant. In the longer term there might be other kinds of names supported.
> 
> > If not, what is the expected way to error out when more variants than `DnsName` exist?
> 
> I guess it would be good to add an `UnsupportedNameType` for the certificate verification callbacks to return. If you agree, could you file an issue or PR?

Hello there, I have trouble understanding/debugging the problem, as I run into this "UnsupportedNameType" error, which has been implemented on above sentiment.

I am using tonic and currently try to establish a TLS connection between ports (localhost) with custom-built self-signed certificates without a CA for simplicity. Does this error mean that I made a mistake when building the certificates? 
I named the X509 certificates "CN: localhost" and added the SAN field in which I specify the value as "localhost". Any help is greatly appreciated @briansmith @djc

**Comment by djc** [comment]
Yeah, if I remember correctly we don't really support self-signed certificates with the default verifier. You can either disable certificate verification or build a little test CA. The latter should be easy enough with the rcgen crate.

If you have any more questions, please open a new issue, since your question doesn't really have anything to do with this issue.
