### ISSUE TITLE
Get the negotiated CipherSuite as a string

### ISSUE THREAD

**Issue by kevinburke** [rustls/rustls#822]
If I compile `psql` (the Postgres command line client) with OpenSSL, the default, and start a repl using TLS, I get the following output:

```
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=#
```

I'm trying to add a rustls backend, but as far as I can tell I can't retrieve the negotiated cipher - `TLS_AES_256_GCM_SHA384 ` - as a string. I tried for example:

```rust
use rustls::internal::msgs::enums::CipherSuite;

fn main() {
    let a = CipherSuite::TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384;
    println!("{}", a.to_string());
}
```

But I get:

```
5   |       println!("{}", a.to_string());
    |                        ^^^^^^^^^ method cannot be called on `CipherSuite` due to unsatisfied trait bounds
    |
   ::: /Users/kevin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/msgs/enums.rs:316:1
    |
316 | / enum_builder! {
317 | |     /// The `CipherSuite` TLS protocol enum.  Values in this enum are taken
318 | |     /// from the various RFCs covering TLS, and are listed by IANA.
319 | |     /// The `Unknown` item is used when processing unrecognised ordinals.
...   |
695 | |     }
696 | | }
    | | -
    | | |
    | |_doesn't satisfy `CipherSuite: ToString`
    |   doesn't satisfy `CipherSuite: std::fmt::Display`
    |
    = note: the following trait bounds were not satisfied:
            `CipherSuite: std::fmt::Display`
            which is required by `CipherSuite: ToString`
```

It would be nice if it was possible to do this, without needing to manually match on the cipher suite name and then print the string. I'm not super great at rust programming, but it seems like here is a possible approach: https://stackoverflow.com/a/50334049/329700, I could try to implement that.

**Comment by djc** [comment]
`CipherSuite` does implement `Debug`, so `format!("{:?}", a)` should work.

**Comment by djc** [comment]
> My understanding is that you're not supposed to use debug formatting in production code?

That's the first I'm hearing about that, I don't think it's a thing in Rust.

https://doc.rust-lang.org/std/fmt/index.html#fmtdisplay-vs-fmtdebug

**Comment by horazont** [comment]
FWIW, I was facing a similar issue the other day. I wanted to have ideally openssl-compatible cipher names (for the most part anyway). That was because the cipher names are exposed as metrics in an existing system (think: number of connections established with TLS version X and cipher Y): https://github.com/horazont/prosody-server-rs/blob/2ce0edebe5f0846b828deca105569424171b360d/src/tls.rs#L399-L446

I wonder if something like that, maybe as a `get_openssl_cipher_name()` function on `SupportedCipherSuite` would be something you'd like to see in rustls? I'd be happy to prepare a PR to add that (and also refine it according to feedback, because I'm sure that this is just a rough approximation).

**Comment by djc** [comment]
@horazont as I explained in https://github.com/rustls/rustls/issues/822#issuecomment-922710428, you can just `format!("{:?}", cs)`, why not use that?

**Comment by horazont** [comment]
@djc I saw that. I see two issues with that, as I require "stable" output. The cipher name is used in a downstream monitoring system, so a change to the cipher name would cause a discontinuity in the data which needs to be then accounted for manually. That could happen if (1) rustls decides to change enumeration member names for any reason or if (2) the output of `{:?}` as generated by `#[derive(Debug)]` changes.

In addition, it would be nice to have a way to get an OpenSSL-compatible cipher name for the ciphers which are supported by rustls, in order to have OpenSSL-compatible output on that front.

That said, I understand if this is a niche case and I'm happy to keep that (rather ugly) `cipher_str` to myself :).

**Comment by djc** [comment]
We don't promise anything about OpenSSL-compatible. What we do have is explicit documentation that the `CipherSuite` variants represent names registered at the IANA with regards to various RFCs. It also seems overly cautious to presume that the derivation of `Debug` for simple enums will ever change to something other than the variant name literal. The only potential issue I see is that you might want to filter out the `Unknown` variant and handle that separately. Otherwise, I don't think there's much value for Rustls to carry another interface for this, when we have a fairly decent mechanism already.

**Comment by horazont** [comment]
Thanks for the reply. That's good enough for me (and where it isn't, I can do things which are specialised like that hack above anyway).
