### ISSUE TITLE
`RootCertStore::add` returns `webpki::Error` as an error

### ISSUE THREAD

**Issue by paolobarbolini** [rustls/rustls#839]
Looks like this was missed in #736

**Comment by briansmith** [comment]
When is the "next major release?"

Because of this problem, it looks like I will need to release a new version of webpki that's semver-compatible with the latest webpki release, which depends on *ring* 0.17 instead of *ring* 0.16.x. This would cause Rustls to depend on both *ring* 0.16.x and 0.17 for most people. That's very undesirable, so then I'll submit a PR to Rustls that updates Rustls to *ring* 0.17 too. Then I hope we can have a new SemVer-compatible release of Rustls promptly after that.

Alternatively, we could just make the next release of Rustls be the one that fixes this bug, if we're willing for that to be a SemVer-breaking release, and if it will happen soon.

**Comment by djc** [comment]
I think it would make sense to do a semver-incompatible release for this. We should probably also get the desired changes to `Error` type variants in before we release it, though.

**Comment by cpu** [comment]
This looks like it was fixed with https://github.com/rustls/rustls/commit/a777077257b4898c996b5e8a641219330d8a7a7a
