### ISSUE TITLE
Support read_buf for efficient reading of plaintext into uninitialized memory

### ISSUE THREAD

**Issue by jsha** [rustls/rustls#872]
`read_buf` (RFC 2930) has landed on nightly:

https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary
https://doc.rust-lang.org/nightly/std/io/struct.ReadBuf.html
https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_buf

It would be useful to have support for this in rustls. In particular, rustls-ffi currently requires that its users fully initialize the buffer passed to `rustls_connection_read`, and face undefined behavior if they don't. This is an unusual requirement for C libraries, and creates a big risk of UB. If we can drop that requirement, we could improve safety for rustls-ffi users, and also potentially improve performance.

**Comment by djc** [comment]
I think we'll wait until it's on stable, or do you think this is important enough that we should have a nightly feature?

**Comment by jsha** [comment]
I think it's worth having a nightly feature, mainly because I'd like to be able to give feedback upstream about whether it meets our needs while the feature is still unstable. I'm assuming it will - lots of smart people have looked at the design - but it's still good to actually test.

**Comment by divergentdave** [comment]
To provide some background on the motivation here, there are two ways `read_buf` can reduce memory initialization overhead, through amortization, or eliminating the need to initialize.

In the most common case, a caller will create a `ReadBuf` with a newly allocated buffer and use it multiple times in `Read::read_buf()` calls. The provided method from the trait will call `ReadBuf::initialize_unfilled()` which initializes the buffer on the first call, and then call `read()` (note that this preserves backwards compatibility). Subsequent calls with the same `ReadBuf` won't pay any costs for buffer initialization, since the `ReadBuf` struct tracks how much of the buffer has been initialized, and `ReadBuf::initialize_unfilled()` can rely on that. Thus, we initialize the buffer once, and amortize that across however many times we call `Read::read_buf() with it.

The new APIs behind the `read_buf` feature also open the door to completely eliminating buffer initialization, though only if the caller and callee are both updated to use `ReadBuf` directly, and the ultimate write or copy into the buffer uses unsafe Rust. (If either the caller or the callee uses `Read::read()`, then we know the buffer must be initialized before that call, as &[u8] cannot point to uninitialized memory) In such an arrangement, the caller would initialize a `ReadBuf` as before, and call `Read::read_buf()`. Then, `<MyType as Read>::read_buf()` would call `ReadBuf::unfilled_mut()`, which returns a mutable slice of `MaybeUninit<u8>`, and convert/cast the slice to a `*mut u8` pointer (and a length). This pointer can then be used with `std::ptr::copy_nonoverlapping()`, `std::ptr::write()`, `libc::read()`, etc. to write to the buffer, in a way that doesn't impose any initialization requirements. Finally, it would call `ReadBuf::assume_init()` and `ReadBuf::set_filled()` to reflect how much had been written. (Three of these function calls are unsafe, `ReadBuf::unfilled_mut()`, `ReadBuf::assume_init()`, and whatever is used to write to the buffer)

With the current, pre-`read_buf`, rustls-ffi API, we leave it to the C caller to initialize the memory, and also leave any amortization of the cost to them. As discussed above, this is unusual, and thus error-prone. We can't readily shift the initialization amortization to `ReadBuf::initialize_unfilled()`, because `rustls_connection_read()` just takes a pointer to a byte buffer and uses it for one read; we'd have to introduce some sort of buffer registration, and require that buffers not be freed while registered.

With the `Read::read_buf()`/unsafe code approach, `rustls_connection_read()` or a successor could relax the requirements on the C caller (now, the memory would only need to be allocated), wrap the buffer with `ReadBuf::uninit()`, and write to it efficiently. Other users of rustls may also see performance benefits. For example, the standard library's `Read::read_to_end()` will use these APIs to avoid buffer initialization where possible.

I took a brief look at the changes that would be required for this. First, we would need a `<rustls::Reader as Read>::read_buf()`, parallel to the existing `<rustls::Reader as Read>::read()`. `Reader` delegates actual reading to `rustls::vecbuf::ChunkVecBuf::read()`, and then does EOF checking. We would thus need to write a new `ChunkVecBuf::read_buf()`, and our unsafe buffer copying code would go here. For as long as this is behind a feature flag, we would need to keep similar logic in these pairs of methods, but once rustls's MSRV advances past stabilization of the feature, each `read()` method could become a wrapper around the `read_buf()` one.

**Comment by ctz** [comment]
Thanks to @divergentdave this is landed on main now. Once support for this is stabilised and present in our MSRV we can likely dispose of the crate feature, but that is likely a year or so away.
