### ISSUE TITLE
Use `Box<dyn std::error::Error>` as the error type for certificate validation errors

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#930]
Right now certificate validation errors have to be formatted into `String` to fit into these variants:
```
    /// We received a certificate which includes invalid data.
    InvalidCertificateData(String),
```
When implementing validators, and especially when testing them, we've found being limited to `String` is unfortunate. For example, imagine a certificate verification library that abstracts over the native Windows, Android, and macOS/iOS certificate validation libraries. It would be nice to be able to retain some of the OS-specific error information, especially the specific error codes returned by the OS, in a way that doesn't require us to parse a `String`.

If we change `InvalidCertificateData(String)` to `Box<dyn std::error::Error>` we can achieve the same effects as we can currently since `std::error::Error: Debug + Display` to provide a validator-implementation-agnostic interface, but also provide the opportunity for callers (tests) to safely downcast (using `Any`) the value to obtain the OS-specific data.

**Comment by Stargateur** [comment]
I would suggest to rework the general variant too based on this proposition.

Currently:
> ```rust
> /// A catch-all error for unlikely errors.
> General(String),
> ```

**Comment by tonyfinn** [comment]
I had hoped to use rustls to check the time until certificate expiration. For a non-expired cert, this information is inspectable through `ClientConnection`, but with the current error layout it's not possible to distinguish an expired cert from other instances of server misbehaviour. For this use case, a expired cert in this case would be effectively another value, in the past, while a protocol error would be a case of not being able to receive a result.. Prior versions of rustls would have allowed detecting this case - the ability to detect this is still documented on the front page of the docs, even though it has been removed by the error refactor.

https://docs.rs/rustls/latest/rustls/

> Any error returned from process_new_packets is fatal to the connection, and will tell you why. For example, if the server’s certificate is expired process_new_packets will return Err(WebPkiError(CertExpired, ValidateServerCert)).

So that's another use case where it would be nice to see underlying error message details.
