### ISSUE TITLE
ECDSA P521 Support

### ISSUE THREAD

**Issue by digitwolf** [rustls/rustls#933]
Hello!

Is there any plan to support P521?

Regards!

**Comment by djc** [comment]
Have a look at https://github.com/briansmith/ring/issues/824, which would be a prerequisite for support in Rustls.

**Comment by digitwolf** [comment]
I feel stupid.I didn't notice that https://docs.rs/rustls/latest/rustls/enum.SignatureScheme.html#variant.ECDSA_NISTP521_SHA512 is already there

**Comment by ctz** [comment]
This is one of the protocol enums, and doesn't imply that rustls supports that. The supported list is: https://github.com/rustls/rustls/blob/main/rustls/src/verify.rs#L20-L33

**Comment by cpu** [comment]
This looks like another issue where we can't make progress from the rustls side unless Ring adds support, or we land alternative backend support as described in https://github.com/rustls/rustls/pull/1184 

I'm going to close this ticket since it can't be addressed in isolation. I suspect making progress on 1184 is the best path towards meeting this feature request.
