### ISSUE TITLE
Any workaround for connecting to an IP address that'd be acceptable?

### ISSUE THREAD

**Issue by farcaller** [rustls/rustls#999]
Given https://github.com/briansmith/webpki/issues/54 is open for 5 years now I don't see webpki supporting IP addresses verification for certificates any time soon. Is there any alternative at all that the maintainers of rustls will find acceptable to implement within rustls to make sure it's usable for connecting to clients based on an IP address alone?

Based on my reading of webpki-0.22.0 there's no way to expose the required data to an external observer for verification. Can you propose an alternative that you'd be willing to review and merge that I could spend my time on implementing?

**Comment by djc** [comment]
Based on my conversations with @briansmith, he is likely to be working on that issue in the relatively short term. You might be interested in #331 for some discussion on a workaround.

**Comment by farcaller** [comment]
Thanks for the context! Unfortunately my use case doesn't allow the workarounds on the configuration side; I'll keep an eye on the discussion happening in this space though.

**Comment by jbg** [comment]
@djc he is always working on it in the relatively short term. Meanwhile PRs from other people are ignored and 5 years later nothing has eventuated. Please please please consider possible alternatives to ring and webpki for rustls, the maintainership of them is really problematic and is holding rustls back. If alternatives don't exist let's look at building them.

**Comment by djc** [comment]
@jbg I am not aware of any PRs for webpki that implemented this and also came with comprehensive testing. If such a PR existed that might make this happen sooner.

**Comment by farcaller** [comment]
Personally I don’t feel like working on a webpki change further as my rather trivial PR for ring that [sorts out the EC private keys encoding](https://github.com/briansmith/ring/pull/1456) is still in the review limbo. The webpki change is not as trivial. I did the preliminary work but it will take time to polish it to something that will be satisfactory for me and in the end I won’t know if there is a chance to push it through. I need some signal that if I work on this then this work isn’t going to be discarded.

**Comment by jbg** [comment]
@djc To be clear I mean that PRs from other people *in general* are ignored, not that there is a ready-to-go PR for this issue that is being ignored. (Though there are PRs that work towards solving this issue, which have not had any feedback.)

It's a recurring issue. I personally worked on adding self-signed certificate support, including tests, after Brian explicitly said he'd be happy to review a PR. My PR was ignored for almost a year and then closed without being merged due to "priorities". People are not going to spend their time to contribute changes if those changes don't get reviewed or even acknowledged.

It's problematic for rustls to have deep dependencies on these libraries. Open the list of merged PRs for webpki or ring and notice that 99% of them are Brian's, yet the list of unmerged PRs contains good work by a variety of contributors that is being completely ignored. This kind of resistance to any outside contribution is harmful.

**Comment by djc** [comment]
@jbg I recognize these issues but I do not have an easy solution for them. webpki contains a substantial amount of very finicky logic that requires a whole bunch of specific knowledge to navigate, and it is obviously very security-sensitive. Bringing up an alternative of similar quality (and with better governance) is a very hard proposition even if a bunch of funding was available.

**Comment by ctz** [comment]
Thanks for the good discussion here. My summary of all this is:

There are two use cases currently unfulfilled by rustls:

1. connecting to public webservers named with IP addresses; there are only few of these but the most notable is https://1.1.1.1/ . This (AIUI) prevents implementation of DoH atop rustls.
3. connecting to internal hosts named with IP addresses (like in the case of a service mesh); the size of this use case is unknowable, but I expect is _larger_ than (1).

We also have near-term goals in rustls which will address these:

- allowing direct use of a system's certificate verification machinery, which would address (1) because in practice these do support IP address names. It would do nothing for (2). This is tricky, though, because this machinery (depending on the platform) does network IO itself and can take multiple seconds as a result. That means we need to add some asynchrony into rustls where there previously was not any. The issue for this is #850 
- supporting IP addresses in certificates when using webpki, which addresses both (1) and (2). The issue for this is #184

To address the other governance question here: should we fork/vendor/abandon webpki and/or ring? I currently strongly think no. This is of course always possible, but it feels like a nuclear option and a dramatic increase in scope in the rustls project. Though I'd give my blessing (not that it should be required!) to people wanting to fork for _rustls_ for exploring this area like building a rustls atop rust-crypto, or rustls atop a port of the golang x509 library, etc.

I hope this message covers the original ask on this issue, so I'm going to close this. But please feel free to continue the discussion on #184 or #850
